### ISSUE TITLE
import file failed, 404 found in error log

### ISSUE THREAD

**Issue by hotraygroup** [uxbox/uxbox#1650]
**To Reproduce**

import https://github.com/penpot/penpot-files/raw/main/Plants-app.penpot failed

**Expected behavior**

**Actual behavior**

A clear and concise description of what happens instead; what the bug is.
 
**Screenshots**

**Desktop (please complete the following information):**
- OS (e.g. iOS):
- Browser & version (e.g. Chrome 89.0):

**Smartphone (please complete the following information):**
- Device & model (e.g. iPhone 6):
- OS & version (e.g. iOS 8.1):
- Browser & version (e.g. stock browser 22):

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance):

*If self-hosted:*
- OS Version (e.g. Ubuntu 16.04): 
- ubuntu 20.04
- Docker / Docker-compose version (e.g. Docker version 18.03.0-ce, build 0520e24):
- 20.10.9-ce
- Image version (e.g. Alpine):
- welcome to penpot" version="1.10.4-beta-6103-gbdfea7cda
penpotapp/exporter   latest    a8eda9ee0c50   12 days ago    1.29GB
penpotapp/frontend   latest    947517670c0f   12 days ago    244MB
penpotapp/backend    latest    ebf40e142b79   8 weeks ago    854MB

Docker commands or docker-compose file (if possible and if proceed.x):
```
---
version: "3.5"

networks:
  penpot:

volumes:
  penpot_postgres_data:
  penpot_assets_data:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
      - 9001:80

    volumes:
      - penpot_assets_data:/opt/data

    env_file:
      - config.env

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - penpot_assets_data:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    env_file:
      - config.env

    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:13"
    restart: always
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

    volumes:
      - penpot_postgres_data:/var/lib/postgresql/data

    networks:
      - penpot

  penpot-redis:
    image: redis:6
    restart: always
    networks:
      - penpot
```

Frontend Stack Trace:
<details>

172.16.0.105 - - [01/Mar/2022:11:53:10 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 216 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:10 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 216 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:10 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 215 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:11 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 216 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:11 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 218 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:11 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 221 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:11 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 218 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:11 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 217 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:11 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 223 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:12 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 215 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:12 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 217 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:12 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 216 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 404 64 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"
172.16.0.105 - - [01/Mar/2022:11:53:40 +0000] "POST /api/rpc/mutation/update-temp-file HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36"

</details>

Backend Stack Trace:
<details>

```

```

</details>

**Additional context:**

Any other context about the problem.
