### ISSUE TITLE
Unable to use the copy function

### ISSUE THREAD

**Issue by AlienHub** [uxbox/uxbox#1870]
**To Reproduce**

1. Open an online file and select Page1 page
2. Select the text control and copy with the shortcut key "Command+C"
3. Select Page2 page, use shortcut key "Command+V" paste

**Expected behavior**

See the file control replicated in Page1 in Page2

**Actual behavior**

Unable to copy

 
**Screenshots**
![image](https://user-images.githubusercontent.com/44266450/167233949-d6641bac-b50b-4b7c-a109-824b685412b9.png)

**Desktop (please complete the following information):**
- OS : Mac OS M1 
- Browser & version :  Chrome 101.0.4951.54 

**Environment (please complete the following information):**
- Host :local instance

*If self-hosted:*
- OS Version: Ubuntu 20.04
- Docker / Docker-compose version: Dcoker version 20.10.14 ,docker-compose version 1.29.2, build unknown
- Image version:  
penpotapp/exporter   latest    e75c159df7f8   2 weeks ago   1.3GB
penpotapp/frontend   latest    336b274a1899   2 weeks ago   243MB
penpotapp/backend    latest    b1fea61e07b0   2 weeks ago   869MB

Docker commands or docker-compose file (if possible and if proceed.x):
```
---
version: "3.5"

networks:
  penpot:


services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
      - 9001:80

    volumes:
      - ./assets_data:/opt/data

    env_file:
      - config.env

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - ./assets_data:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    env_file:
      - config.env

    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:13"
    restart: always
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

    volumes:
      - ./postgres:/var/lib/postgresql/data

    networks:
      - penpot

  penpot-redis:
    image: redis:6
    restart: always
    networks:
      - penpot
```

**Additional context:**

Penpot copy component, error
