### ISSUE TITLE
Text alignment becomes undefined after pasting text from clipboard

### ISSUE THREAD

**Issue by inexcode** [uxbox/uxbox#2007]
**To Reproduce**

1.  Create a text field, enter some text, align it by right side or center.
2.  Paste some text from clipboard.
3.  Text becomes aligned by left side.

**Expected behavior**

Text alignment stays the same.

**Actual behavior**

Text aligns by left side and no alignment button is activated.

**Screenshots**

![image](https://user-images.githubusercontent.com/13254627/174350362-e3a9b30d-e1b4-4208-9899-4c81901d7433.png)
![image](https://user-images.githubusercontent.com/13254627/174350415-57e92941-e385-464d-a466-dd7517535ecf.png)

**Desktop:**
- OS: NixOS 22.05
- Browser & version: Firefox 101.0.1

**Environment:**
- Host: Self-hosted
- OS Version (e.g. Ubuntu 16.04): Ubuntu 20.04.4
- Docker / Docker-compose version: docker-compose version 1.25.0, docker version 20.10.17
- Image version (e.g. Alpine): latest (Beta 1.13)

Docker commands or docker-compose file (if possible and if proceed.x):
<details>

```yaml
---
version: "3.5"

networks:
  traefik:
    external: true
  mailinexdev_default:
    external: true
  penpot:

volumes:
  penpot_postgres_data:
  penpot_assets_data:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    volumes:
      - penpot_assets_data:/opt/data
    env_file:
      - config.env
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot
      - traefik
    restart: "unless-stopped"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.penpot.rule=Host(`penpot.inex.dev`)"
      - "traefik.http.routers.penpot.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.penpot.entrypoints=websecure"
      - "traefik.http.services.penpont.loadbalancer.server.port=80"

  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - penpot_assets_data:/opt/data
    depends_on:
      - penpot-postgres
      - penpot-redis
    env_file:
      - config.env
    networks:
      - penpot
      - mailinexdev_default
    restart: "unless-stopped"

  penpot-exporter:
    restart: "unless-stopped"
    image: "penpotapp/exporter:latest"
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:13"
    restart: always
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    volumes:
      - penpot_postgres_data:/var/lib/postgresql/data
    networks:
      - penpot
    restart: "unless-stopped"

  penpot-redis:
    image: redis:6
    restart: "unless-stopped"
    networks:
      - penpot

```
</details>
