### ISSUE TITLE
Try to use penpot with custom volume and external database (postgres on host and not in docker)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [uxbox/uxbox#2237]
**To Reproduce**

I have customize my docker-compose.yml to not used postgres with docker and use custom volume.
I have edited the config.env file.

**Expected behavior**

Better explicit message or something to understand if I do something wrong.

**Actual behavior**

At present, when I start docker-compose, I can seen this error

~~~
Attaching to penpot_penpot-exporter_1, penpot_penpot-redis_1, penpot_penpot-backend_1, penpot_penpot-frontend_1
penpot-backend_1   | + exec /usr/lib/jvm/openjdk/bin/java -jar penpot.jar -m app.main
penpot-exporter_1  | INF [app.core] msg="initializing"
penpot-redis_1     | 1:C 06 Sep 2022 16:27:49.206 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
penpot-redis_1     | 1:C 06 Sep 2022 16:27:49.206 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
penpot-redis_1     | 1:C 06 Sep 2022 16:27:49.206 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
penpot-exporter_1  | INF [app.browser] hint="initializing browser pool", opts=#js {:max 5, :min 0, :testOnBorrow true, :evictionRunIntervalMillis 5000, :numTestsPerEvictionRun 5, :acquireTimeoutMillis 10000, :idleTimeoutMillis 10000}
penpot-redis_1     | 1:M 06 Sep 2022 16:27:49.206 * monotonic clock: POSIX clock_gettime
penpot-exporter_1  | INF [app.http] hint="welcome to penpot", module="exporter", version="1.15.2-beta-7851-g2cb8e7b98"
penpot-redis_1     | 1:M 06 Sep 2022 16:27:49.206 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
penpot-exporter_1  | INF [app.http] hint="starting http server", port=6061
penpot-redis_1     | 1:M 06 Sep 2022 16:27:49.206 * Running mode=standalone, port=6379.
penpot-exporter_1  | INF [app.redis] hint="redis connection established", uri="redis://penpot-redis/0"
penpot-redis_1     | 1:M 06 Sep 2022 16:27:49.206 # Server initialized
penpot-redis_1     | 1:M 06 Sep 2022 16:27:49.206 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
penpot-redis_1     | 1:M 06 Sep 2022 16:27:49.207 * Loading RDB produced by version 6.2.7
penpot-redis_1     | 1:M 06 Sep 2022 16:27:49.207 * RDB age 127 seconds
penpot-redis_1     | 1:M 06 Sep 2022 16:27:49.207 * RDB memory usage when created 0.79 Mb
penpot-redis_1     | 1:M 06 Sep 2022 16:27:49.207 # Done loading RDB, keys loaded: 0, keys expired: 0.
penpot-redis_1     | 1:M 06 Sep 2022 16:27:49.207 * DB loaded from disk: 0.000 seconds
penpot-redis_1     | 1:M 06 Sep 2022 16:27:49.207 * Ready to accept connections
penpot-backend_1   | [2022-09-06 16:27:51.026] I app.config - hint="flags initialized", flags="backend-api-doc,secure-session-cookies,login,backend-worker,registration"
penpot-backend_1   | WARNING: abs already refers to: #'clojure.core/abs in namespace: taoensso.encore, being replaced by: #'taoensso.encore/abs
penpot-backend_1   | [2022-09-06 16:27:53.332] I app.metrics - action="initialize metrics"
penpot-backend_1   | Execution error (SQLException) at java.sql.DriverManager/getDriver (DriverManager.java:300).
penpot-backend_1   | No suitable driver
penpot-backend_1   | 
penpot-backend_1   | Full report at:
penpot-backend_1   | /tmp/clojure-16251214982237938397.edn
penpot_penpot-backend_1 exited with code 1
~~~
I just seen this. The frontend works good because I seen message about  `Bad Gateway`.

And in the `/tmp/clojure-16251214982237938397.edn` (I have added a volume to save this file on host). This is the beggining of the file:
~~~
{:clojure.main/message
 "Execution error (SQLException) at java.sql.DriverManager/getDriver (DriverManager.java:300).\nNo suitable driver\n",
 :clojure.main/triage
 {:clojure.error/class java.sql.SQLException,
  :clojure.error/line 300,
  :clojure.error/cause "No suitable driver",
  :clojure.error/symbol java.sql.DriverManager/getDriver,
  :clojure.error/source "DriverManager.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.ExceptionInfo,
    :message "Error on key :app.db/pool when building system",
    :data
    {:reason :integrant.core/build-threw-exception,
     :system
     {:app.migrations/all
~~~

**Screenshots**

**Desktop (please complete the following information):**
- OS (e.g. iOS): Ubuntu 
- Browser & version (e.g Chrome 89.0): Firefox 104 

**Smartphone (please complete the following information):**
- Device & model (e.g. iPhone 6):
- OS & version (e.g. iOS 8.1):
- Browser & version (e.g. stock browser 22):

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): 

*If self-hosted:*
- OS Version (e.g. Ubuntu 16.04): debian 11
- reverse proxy : on debian 9 (proxy nginx)
- Docker / Docker-compose version (e.g. Docker version 18.03.0-ce, build 0520e24):  `Docker version 20.10.17, build 100c701` / `docker-compose version 1.29.2, build 5becea4c`
- Image version (e.g. Alpine): latest (use this documentation https://help.penpot.app/technical-guide/getting-started/#start-penpot for the moment and default config for image in docker-compose.yml)

Docker commands or docker-compose file (if possible and if proceed.x):
```
docker-compose -p penpot -f /root/docker-compose-penpot.yaml up
```
```
---
version: "3.5"

networks:
  penpot:

#volumes:
#  penpot_postgres_data:
#  penpot_assets_data:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
      - *.*.*.*:12020:80
    volumes:
      - /data/services/penpot/penpot_assets_data:/opt/data
    env_file:
      - /data/services/penpot/config.env
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - /data/services/penpot/penpot_assets_data:/opt/data
      - /tmp/penpot-tmp:/tmp
    depends_on:
#      - penpot-postgres
      - penpot-redis
    env_file:
      - /data/services/penpot/config.env
    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    env_file:
      - /data/services/penpot/config.env
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

#  penpot-postgres:
#    image: "postgres:13"
#    restart: always
#    stop_signal: SIGINT
#    environment:
#      - POSTGRES_INITDB_ARGS=--data-checksums
#      - POSTGRES_DB=penpot
#      - POSTGRES_USER=penpot
#      - POSTGRES_PASSWORD=penpot
#    volumes:
#      - penpot_postgres_data:/var/lib/postgresql/data
#    networks:
#      - penpot

  penpot-redis:
    image: redis:6
    restart: always
    networks:
      - penpot                                                                       
```

Frontend Stack Trace:
<details>

```

```

</details>

Backend Stack Trace:
<details>

```

```

</details>

**Additional context:**

Any other context about the problem.
