### ISSUE TITLE
bug: Images/Assets not working

### ISSUE THREAD

**Issue by Rod-O** [uxbox/uxbox#2501]
### Steps To Reproduce

I setup the backend using Docker and the recommended setting:
https://help.penpot.app/technical-guide/configuration/#storage
Doing some research I noticed the assets are being stored in /opt/penpot/backend/assets:
```
root@273057141afe:/opt/penpot/backend/assets# ls
1e  38  8f  ac  bc
```
but nothing under /opt/data:
```
root@273057141afe:/opt/data# ls
root@273057141afe:/opt/data#
```

### Expected behavior

Images working as usual

### Actual behavior

All images are a 404

### Screenshots or video

Docker compose file:
```
version: "3.5"

networks:
  penpot:

volumes:
  penpot_postgres_data:
  penpot_assets_data:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
      - 9001:80

    volumes:
      - penpot_assets_data:/opt/data

    environment:
      - PENPOT_FLAGS=${PENPOT_FLAGS}
      - PENPOT_PUBLIC_URI=${PENPOT_PUBLIC_URI}
      - PENPOT_DATABASE_URI=${PENPOT_DATABASE_URI}
      - PENPOT_DATABASE_USERNAME=${PENPOT_DATABASE_USERNAME}
      - PENPOT_DATABASE_PASSWORD=${PENPOT_DATABASE_PASSWORD}
      - PENPOT_REDIS_URI=${PENPOT_REDIS_URI}
      - PENPOT_STORAGE_BACKEND=${PENPOT_STORAGE_BACKEND}
      - PENPOT_STORAGE_FS_DIRECTORY=${PENPOT_STORAGE_FS_DIRECTORY}
      - PENPOT_TELEMETRY_ENABLED=${PENPOT_TELEMETRY_ENABLED}
      - PENPOT_TELEMETRY_WITH_TAIGA=${PENPOT_TELEMETRY_WITH_TAIGA}
      - PENPOT_REGISTRATION_ENABLED=${PENPOT_REGISTRATION_ENABLED}
      - PENPOT_ALLOW_DEMO_USERS=${PENPOT_ALLOW_DEMO_USERS}
      # Open ID
      - PENPOT_OIDC_CLIENT_ID=${PENPOT_OIDC_CLIENT_ID}


    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot
    restart: always
  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - penpot_assets_data:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    environment:
      - PENPOT_FLAGS=${PENPOT_FLAGS}
      - PENPOT_PUBLIC_URI=${PENPOT_PUBLIC_URI}
      - PENPOT_DATABASE_URI=${PENPOT_DATABASE_URI}
      - PENPOT_DATABASE_USERNAME=${PENPOT_DATABASE_USERNAME}
      - PENPOT_DATABASE_PASSWORD=${PENPOT_DATABASE_PASSWORD}
      - PENPOT_REDIS_URI=${PENPOT_REDIS_URI}
      - PENPOT_STORAGE_BACKEND=${PENPOT_STORAGE_BACKEND}
      - PENPOT_STORAGE_FS_DIRECTORY=${PENPOT_STORAGE_FS_DIRECTORY}
      - PENPOT_TELEMETRY_ENABLED=${PENPOT_TELEMETRY_ENABLED}
      - PENPOT_TELEMETRY_WITH_TAIGA=${PENPOT_TELEMETRY_WITH_TAIGA}
      - PENPOT_REGISTRATION_ENABLED=${PENPOT_REGISTRATION_ENABLED}
      - PENPOT_ALLOW_DEMO_USERS=${PENPOT_ALLOW_DEMO_USERS}
      #Open ID
      - PENPOT_OIDC_CLIENT_ID=${PENPOT_OIDC_CLIENT_ID}
      - PENPOT_OIDC_BASE_URI=https://login.microsoftonline.com/${PENPOT_OIDC_TENANT_ID}/v2.0/
      - PENPOT_OIDC_CLIENT_SECRET=${PENPOT_OIDC_CLIENT_SECRET}
      # SMTP
      - PENPOT_SMTP_DEFAULT_FROM=${PENPOT_SMTP_DEFAULT_FROM}
      - PENPOT_SMTP_DEFAULT_REPLY_TO=${PENPOT_SMTP_DEFAULT_REPLY_TO}
      - PENPOT_SMTP_HOST=${PENPOT_SMTP_HOST}
      - PENPOT_SMTP_PORT=${PENPOT_SMTP_PORT}
      - PENPOT_SMTP_USERNAME=${PENPOT_SMTP_USERNAME}
      - PENPOT_SMTP_PASSWORD=${PENPOT_SMTP_PASSWORD}
      - PENPOT_SMTP_TLS=${PENPOT_SMTP_TLS}
      
    networks:
      - penpot
    restart: always
  penpot-exporter:
    image: "penpotapp/exporter:latest"
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot
    restart: always
  penpot-postgres:
    image: "postgres:13"
    restart: always
    stop_signal: SIGINT
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot
    volumes:
      - penpot_postgres_data:/var/lib/postgresql/data
    networks:
      - penpot
    ports:
      - 5435:5432


  penpot-redis:
    image: redis:6
    restart: always
    networks:
      - penpot
```
