### ISSUE TITLE
bug: Invite members: button wrong size

### ISSUE THREAD

**Issue by feurer98** [uxbox/uxbox#2668]
### Steps To Reproduce

Fresh Docker installation 
Version 1.16.0-beta

```
---
version: "3.5"

networks:
  penpot:

volumes:
  penpot_postgres_data:
  penpot_assets_data:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
      - 9050:80

    volumes:
      - /volume1/docker/penpot/data-front:/opt/data

    env_file:
      - config.env

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - /volume1/docker/penpot/data-backend:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    env_file:
      - config.env

    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    env_file:
      - config.env
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:latest"
    restart: always
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

    volumes:
      - /volume1/docker/penpot/db:/var/lib/postgresql/data

    networks:
      - penpot

  penpot-redis:
    image: redis:6
    restart: always
    networks:
      - penpot
```

### Expected behavior

nice gui, text fitting

### Actual behavior

see screenshot below

### Screenshots or video

![image](https://user-images.githubusercontent.com/45851500/207895493-c5b8265b-ea01-470a-b020-5342248a8626.png)

### Desktop (please complete the following information)

Microsoft Edge
Version 108.0.1462.46 (Offizielles Build) (64-Bit)
