### ISSUE TITLE
bug: Redirect to Login Screen after OpenID Authentication

### ISSUE THREAD

**Issue by Dan6erbond** [uxbox/uxbox#2819]
### Steps To Reproduce

I configured Penpot with OIDC using Authentik as my IdP. This initially seemed to work, until I just kept getting the redirect to the login screen after trying to change various parameters to get S3 working. The problem is I don't know what parameter might have caused this bug. At first I assumed it might be related to disabling registration, so I tried enabling, re-deployed and it still doesn't work. I also have no useful logs in the penpot-backend container making it pretty hard to find out if it's because of an OAuth scope issue or something else. 

These are the environment variables I have set for OIDC:

```
PENPOT_OIDC_CLIENT_SECRET = authentik_provider_oauth2.penpot_oidc_provider.client_secret
PENPOT_OIDC_CLIENT_ID = authentik_provider_oauth2.penpot_oidc_provider.client_id
PENPOT_OIDC_BASE_URI  = "${var.authentik_url}/application/o/${authentik_application.penpot.slug}/"
PENPOT_OIDC_SCOPES    = "openid profile email"
```

And the Penpot flags:

```
disable-registration disable-login disable-email-verification enable-login-with-oidc disable-demo-users disable-demo-warning
```

### Expected behavior

Log-into Penpot with OIDC.

### Actual behavior

Redirect to login screen.

### Frontend Stack Trace

```console
10.42.0.193 - - [21/Jan/2023:18:35:47 +0000] "POST /api/auth/oauth/oidc HTTP/1.1" 200 442 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
10.42.0.193 - - [21/Jan/2023:18:35:48 +0000] "GET /api/auth/oauth/oidc/callback?code=code&state=state HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
```

### Backend Stack Trace

This is kind of what I would like to find out how I can get something useful. I'm only seeing the initial Penpot migrations and configuration output in Kubernetes logs.

### Additional context

It would already be super helpful, if I could find out what kind of error Penpot is throwing when it tries to sign me up, because the logs aren't giving me that information, and I don't know if it's unhappy with the OIDC secret, scopes or something else. Thanks!

**Comment by te0dor24** [comment]
why demo?

**Comment by niwinz** [comment]
You can safely remove `disable-email-verification` because you already have registration disabled.
You can safely remove `disable-demo-users`and  `disable-demo-warning`, they are already disabled by default.
You will need to replace `disable-login` with `disable-login-with-password` (the doc was outdated and it will be fixed ASAP).

Now, for understand what happens with OIDC, we need a backend logs.  I'm not be able to guess what is going on without more info. Each oauth provider has its own quirks unfortunatelly

**Comment by Dan6erbond** [comment]
Is there a way to increase backend logging level? I don't see any output that could explain why OIDC doesn't work. After shortly getting OIDC working again, some changes in the configuration result in it happening again. I made sure that my users have their emails set and such. So the OIDC claims are all there.

**Comment by Dan6erbond** [comment]
Oh, I should mention that login works for me. Just all the users I asked to test aren't able to log-in. Do I need to invite them somehow?

**Comment by Dan6erbond** [comment]
Hmm, looking into it a bit more. The Authentik admin account used to have my email address set, and logging in with it worked. Then I switched it to a different email and it stopped working. So I'm guessing it's only allowing me to log-in right now. What could be causing this?

**Comment by naim5am** [comment]
> 



> You will need to replace `disable-login` with `disable-login-with-password` (the doc was outdated and it will be fixed ASAP).

I did that, not sure if this is a bug but my issue is kinda related, though I'm not using OpenID. I'm just trying to run penpot locally but I keep getting stuck at **Great to see you again!** ; i.e. http://localhost:9001/#/auth/login 
I'm don't see any errors in the logs. Not sure how to fix this. Here's my config file, maybe you can see something wrong.
_or maybe I should open a new bug report?_

```
---
version: "3.5"

networks:
  penpot:

volumes:
  penpot_postgres_v15:
  penpot_assets:

services:

  penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
      - 9001:80

    volumes:
      - penpot_assets:/opt/penpot/assets

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

    labels:
      - "traefik.enable=true"

    environment:

      - PENPOT_FLAGS=disable-registration disable-login-with-password

  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - penpot_assets:/opt/penpot/assets

    depends_on:
      - penpot-postgres
      - penpot-redis

    networks:
      - penpot

    environment:

      - PENPOT_FLAGS=disable-registration enable-insecure-register disable-login-with-password enable-smtp enable-prepl-server

      - PENPOT_SECRET_KEY=EfiHWUPQHnyUUQKBz4SzEUoXCRmGys57-2mhffre2154GER3fkikFSw0jPpTNlOz10gizw_wFDkUZTp6ohj08g


      - PENPOT_PUBLIC_URI=http://localhost:9001


      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot

      - PENPOT_REDIS_URI=redis://penpot-redis/0

      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/penpot/assets

      - PENPOT_TELEMETRY_ENABLED=true

      - PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      - PENPOT_SMTP_HOST=penpot-mailcatch
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_USERNAME=
      - PENPOT_SMTP_PASSWORD=
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    networks:
      - penpot

    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT

    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data

    networks:
      - penpot

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot

  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
```
full logs:: 

```
docker compose -p penpot -f docker-compose.yaml up
[+] Running 6/0
 ⠿ Container penpot-penpot-postgres-1   Running                                                                                                                                          0.0s
 ⠿ Container penpot-penpot-redis-1      Running                                                                                                                                          0.0s
 ⠿ Container penpot-penpot-mailcatch-1  Running                                                                                                                                          0.0s
 ⠿ Container penpot-penpot-exporter-1   Created                                                                                                                                          0.0s
 ⠿ Container penpot-penpot-backend-1    Created                                                                                                                                          0.0s
 ⠿ Container penpot-penpot-frontend-1   Created                                                                                                                                          0.0s
Attaching to penpot-penpot-backend-1, penpot-penpot-exporter-1, penpot-penpot-frontend-1, penpot-penpot-mailcatch-1, penpot-penpot-postgres-1, penpot-penpot-redis-1
penpot-penpot-backend-1    | + exec /opt/jdk/bin/java -jar penpot.jar -m app.main
penpot-penpot-exporter-1   | INF [app.core] msg="initializing", public-uri="http://penpot-frontend", version="1.17.0-9304-g7ab91f68a"
penpot-penpot-exporter-1   | INF [app.browser] hint="initializing browser pool", opts=#js {:max 5, :min 0, :testOnBorrow true, :evictionRunIntervalMillis 5000, :numTestsPerEvictionRun 5, :acquireTimeoutMillis 10000, :idleTimeoutMillis 10000}
penpot-penpot-exporter-1   | INF [app.http] hint="welcome to penpot", module="exporter", version="1.17.0-9304-g7ab91f68a"
penpot-penpot-exporter-1   | INF [app.http] hint="starting http server", port=6061
penpot-penpot-exporter-1   | INF [app.redis] hint="redis connection established", uri="redis://penpot-redis/0"
penpot-penpot-backend-1    | [2023-02-06 11:28:22.793] I app.metrics - action="initialize metrics"
penpot-penpot-backend-1    | [2023-02-06 11:28:22.850] I app.db - hint="initialize connection pool", name="main", uri="postgresql://penpot-postgres/penpot", read-only=false, with-credentials=true, min-size=0, max-size=60
penpot-penpot-backend-1    | [2023-02-06 11:28:23.263] I app.redis - hint="initialize redis resources", uri="redis://penpot-redis/0", io-threads=4, worker-threads=4, connect?=nil
penpot-penpot-backend-1    | [2023-02-06 11:28:23.473] I app.msgbus - hint="initialize msgbus", buffer-size=128
penpot-penpot-backend-1    | [2023-02-06 11:28:24.004] I app.setup.builtin-templates - hint="loading template files", total=9
penpot-penpot-backend-1    | [2023-02-06 11:28:24.490] I app.http - hint="starting http server", port=6060, host="0.0.0.0", name="http"
penpot-penpot-backend-1    | [2023-02-06 11:28:24.514] I io.undertow - starting server: Undertow - 2.3.0.Final
penpot-penpot-backend-1    | [2023-02-06 11:28:24.521] I org.xnio - XNIO version 3.8.8.Final
penpot-penpot-backend-1    | [2023-02-06 11:28:24.530] I org.xnio.nio - XNIO NIO Implementation Version 3.8.8.Final
penpot-penpot-backend-1    | [2023-02-06 11:28:24.548] I org.jboss.threads - JBoss Threads version 3.5.0.Final
penpot-penpot-backend-1    | [2023-02-06 11:28:24.591] I app.loggers.zmq - hint="receiver started"
penpot-penpot-backend-1    | [2023-02-06 11:28:24.594] I app.loggers.database - hint="initializing database error persistence"
penpot-penpot-backend-1    | [2023-02-06 11:28:24.602] I app.storage.tmp - hint="started tmp file cleaner"
penpot-penpot-backend-1    | [2023-02-06 11:28:24.624] I app.worker - hint="registry initialized", tasks=13
penpot-penpot-backend-1    | [2023-02-06 11:28:24.634] I app.worker - hint="cron: started", tasks=8
penpot-penpot-backend-1    | [2023-02-06 11:28:24.678] I app.worker - hint="dispatcher: started"
penpot-penpot-backend-1    | [2023-02-06 11:28:24.690] I app.worker - hint="monitor: started", name="default"
penpot-penpot-backend-1    | [2023-02-06 11:28:24.701] I app.worker - hint="worker: started", worker-id=0, queue="default"
penpot-penpot-backend-1    | [2023-02-06 11:28:24.704] I app.worker - hint="worker: started", worker-id=0, queue="webhooks"
penpot-penpot-backend-1    | [2023-02-06 11:28:24.705] I app.srepl - msg="initializing repl server", name="prepl", port=6063, host="localhost"
penpot-penpot-backend-1    | [2023-02-06 11:28:24.713] I app.main - hint="welcome to penpot", flags="backend-api-doc,secure-session-cookies,backend-worker,smtp,email-verification,prepl-server", worker?=true, version="1.17.0-9304-g7ab91f68a"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:23 +0000] "GET / HTTP/1.1" 200 333318 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:23 +0000] "GET /css/main-default.css?ts=1675202944376 HTTP/1.1" 200 57721 "http://localhost:9001/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:23 +0000] "GET /js/config.js?ts=1675202944865 HTTP/1.1" 200 111 "http://localhost:9001/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:23 +0000] "GET /js/polyfills.js?ts=1675202944865 HTTP/1.1" 200 1015 "http://localhost:9001/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:23 +0000] "GET /js/shared.7ab91f68a.js HTTP/1.1" 200 811652 "http://localhost:9001/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:23 +0000] "GET /js/main.7ab91f68a.js HTTP/1.1" 200 788812 "http://localhost:9001/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:24 +0000] "GET /images/favicon.png HTTP/1.1" 200 1336 "http://localhost:9001/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:24 +0000] "GET /js/worker.7ab91f68a.js HTTP/1.1" 200 52394 "http://localhost:9001/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:25 +0000] "GET /api/rpc/query/profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:25 +0000] "GET /images/login-penpot.svg HTTP/1.1" 200 267566 "http://localhost:9001/css/main-default.css?ts=1675202944376" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:25 +0000] "GET /fonts/WorkSans-Medium.woff2 HTTP/1.1" 200 76068 "http://localhost:9001/css/main-default.css?ts=1675202944376" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:25 +0000] "GET /fonts/WorkSans-Regular.woff2 HTTP/1.1" 200 71416 "http://localhost:9001/css/main-default.css?ts=1675202944376" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:26 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:27 +0000] "GET /api/rpc/query/profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:28 +0000] "GET /api/rpc/query/profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-penpot-postgres-1   | 2023-02-06 11:29:49.365 UTC [27] LOG:  checkpoint starting: time
penpot-penpot-postgres-1   | 2023-02-06 11:29:49.500 UTC [27] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.105 s, sync=0.008 s, total=0.136 s; sync files=2, longest=0.005 s, average=0.004 s; distance=3 kB, estimate=3 kB
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:55 +0000] "GET / HTTP/1.1" 200 333318 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:55 +0000] "GET /js/config.js?ts=1675202944865 HTTP/1.1" 200 111 "http://localhost:9001/" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:55 +0000] "GET /css/main-default.css?ts=1675202944376 HTTP/1.1" 200 57721 "http://localhost:9001/" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:55 +0000] "GET /js/polyfills.js?ts=1675202944865 HTTP/1.1" 200 1015 "http://localhost:9001/" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:55 +0000] "GET /js/shared.7ab91f68a.js HTTP/1.1" 200 811652 "http://localhost:9001/" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:55 +0000] "GET /js/main.7ab91f68a.js HTTP/1.1" 200 788812 "http://localhost:9001/" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:56 +0000] "GET /images/favicon.png HTTP/1.1" 200 1336 "http://localhost:9001/" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:56 +0000] "GET /api/rpc/query/profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:56 +0000] "GET /js/worker.7ab91f68a.js HTTP/1.1" 200 52394 "http://localhost:9001/" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:57 +0000] "GET /api/rpc/query/profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:57 +0000] "GET /images/login-penpot.svg HTTP/1.1" 200 267566 "http://localhost:9001/css/main-default.css?ts=1675202944376" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:57 +0000] "GET /fonts/WorkSans-Medium.woff2 HTTP/1.1" 200 76068 "http://localhost:9001/css/main-default.css?ts=1675202944376" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
penpot-penpot-frontend-1   | 172.18.0.1 - - [06/Feb/2023:11:29:57 +0000] "GET /fonts/WorkSans-Regular.woff2 HTTP/1.1" 200 71416 "http://localhost:9001/css/main-default.css?ts=1675202944376" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
```
