### ISSUE TITLE
bug: Error on template import

### ISSUE THREAD

**Issue by 0xb1b1** [uxbox/uxbox#2876]
### Steps To Reproduce

1. Go to the main page of your self-hosted Penpot instance (Docker + Traefik)
2. Open "Libraries & Templates"
3. Select a template (confirmed on "Circum Icons pack", "Material Design (baseline)") > "Continue"
4. Get the error "There was a problem importing the template. The template wasn't imported."

### Expected behavior

Theme is added to Drafts

### Actual behavior

An error occurs on the backend

### Desktop (please complete the following information)

- MacOS Ventura 13.2
- Firefox 109.0 (64-bit) ARM64

### Environment (please complete the following information)

- Self-hosted instance

- NixOS 22.05
- Docker 20.10.18 on arch linux/amd64, containerd v1.6.4, runc 1.1.4, docker-init 0.19.0
  Portainer Community Edition 2.16.2
- Docker Images:
  penpot/backend:latest @ sha256:499ed0ae2aca17363b79f6e33cd4bdad5ace79dbee42fcfaf9520aff7f5f9a06
  penpot/frontend:latest @ sha256:a52c0fc2dc9ee81a65dfc46ee95886018c6c8daa117506a11d2a2da52ebd3ead
  penpot/exporter:latest @ sha256:2d5fd2f4a07fd36b2d3b7633704236823db5d1dcf7d538c63a6fb04ec1183377

- Docker Compose:
```
---
version: "3.5"

volumes:
  db:
  assets:
  mailcatcher:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    volumes:
      - "assets:/opt/data"
    depends_on:
      - penpot-backend
      - penpot-exporter
    labels:
      - "traefik.http.routers.penpot_http.rule=Host(`<REDACTED>`)"
      - "traefik.http.routers.penpot_http.entrypoints=web"
      - "traefik.http.routers.penpot_http.middlewares=redirect-to-https"

      - "traefik.http.routers.penpot.rule=Host(`<REDACTED>`)"
      - "traefik.http.routers.penpot.entrypoints=websecure"
      - "traefik.http.routers.penpot.tls=true"
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always
    volumes:
      - "assets:/opt/data"
    depends_on:
      - penpot-postgres
      - penpot-redis
    environment:
      - PENPOT_FLAGS=enable-registration enable-login disable-email-verification enable-smtp
      - PENPOT_PUBLIC_URI=${PENPOT_PUBLIC_URI}
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=$POSTGRES_PASSWORD
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=false

      - PENPOT_SMTP_DEFAULT_FROM=${PENPOT_SMTP_DEFAULT_FROM}
      - PENPOT_SMTP_DEFAULT_REPLY_TO=${PENPOT_SMTP_DEFAULT_REPLY_TO}
      - PENPOT_SMTP_HOST=penpot-mailcatcher
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_USERNAME=
      - PENPOT_SMTP_PASSWORD=
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  penpot-redis:
    image: redis:7
    restart: always

  penpot-mailcatcher:
    image: jgiannuzzi/mailcatcher:latest
    restart: always
    volumes:
      - "mailcatcher:/data"
    labels:
      - "traefik.http.routers.penpot_mailcatch_http.rule=Host(`<REDACTED>`)"
      - "traefik.http.routers.penpot_mailcatch_http.entrypoints=web"
      - "traefik.http.routers.penpot_mailcatch_http.middlewares=redirect-to-https"

      - "traefik.http.services.penpot_mailcatch.loadbalancer.server.port=1080"
      - "traefik.http.routers.penpot_mailcatch.rule=Host(`penpot-mailcatch.<REDACTED>`)"
      - "traefik.http.routers.penpot_mailcatch.entrypoints=websecure"
      - "traefik.http.routers.penpot_mailcatch.tls=true"

```

### Backend Stack Trace

```console
[2023-01-31 23:18:57.815] I app.main - hint="welcome to penpot", flags="login-with-password,backend-api-doc,secure-session-cookies,login,backend-worker,smtp,registration", worker?=true, version="1.17.0-9304-g7ab91f68a"
[2023-01-31 23:25:31.282] I app.rpc.commands.binfile - hint="import: started", import-id=#uuid "648245e8-8bf8-810e-8001-fdcdafc463cf"
[2023-01-31 23:25:32.397] I app.rpc.commands.binfile - hint="import: terminated", import-id=#uuid "648245e8-8bf8-810e-8001-fdcdafc463cf", elapsed="1.10975747s", error?=true
TRACE:
 →  java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: /opt/data/assets (CompletableFuture.java:396)
 →  java.nio.file.AccessDeniedException: /opt/data/assets (UnixException.java:90)
DETAIL:
 →  java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: /opt/data/assets (CompletableFuture.java:396)
    at: java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        clojure.core$deref_future.invokeStatic(core.clj:2317)
        clojure.core$deref.invokeStatic(core.clj:2337)
        clojure.core$deref.invoke(core.clj:2323)
        app.rpc.commands.binfile$fn__31845.invokeStatic(binfile.clj:713)
        app.rpc.commands.binfile/fn(binfile.clj:697)
        clojure.lang.MultiFn.invoke(MultiFn.java:229)
        app.rpc.commands.binfile$fn__31742$fn__31744$fn__31745.invoke(binfile.clj:599)
        clojure.core$run_BANG_$fn__8880.invoke(core.clj:7783)
        clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        clojure.core$reduce.invokeStatic(core.clj:6885)
        clojure.core$run_BANG_.invokeStatic(core.clj:7778)
        clojure.core$run_BANG_.invoke(core.clj:7778)
        app.rpc.commands.binfile$fn__31742$fn__31744.invoke(binfile.clj:591)
        next.jdbc.transaction$transact_STAR_.invokeStatic(transaction.clj:72)
        next.jdbc.transaction$transact_STAR_.invoke(transaction.clj:51)
        next.jdbc.transaction$fn__7332.invokeStatic(transaction.clj:136)
        next.jdbc.transaction/fn(transaction.clj:115)
        next.jdbc.protocols$fn__6141$G__6136__6150.invoke(protocols.clj:58)
        next.jdbc$transact.invokeStatic(jdbc.clj:381)
        next.jdbc$transact.invoke(jdbc.clj:373)
        app.rpc.commands.binfile$fn__31742.invokeStatic(binfile.clj:588)
        app.rpc.commands.binfile/fn(binfile.clj:584)
        clojure.lang.MultiFn.invoke(MultiFn.java:229)
        app.rpc.commands.binfile$read_import_BANG_.invokeStatic(binfile.clj:582)
        app.rpc.commands.binfile$read_import_BANG_.invoke(binfile.clj:564)
        app.rpc.commands.binfile$import_BANG_.invokeStatic(binfile.clj:875)
        app.rpc.commands.binfile$import_BANG_.invoke(binfile.clj:866)
        app.rpc.commands.management$clone_template.invokeStatic(management.clj:411)
        app.rpc.commands.management$clone_template.invoke(management.clj:394)
        app.rpc.commands.management$sm$clone_template$fn__42188.invoke(management.clj:392)
        next.jdbc.transaction$transact_STAR_.invokeStatic(transaction.clj:72)
        next.jdbc.transaction$transact_STAR_.invoke(transaction.clj:51)
        next.jdbc.transaction$fn__7332.invokeStatic(transaction.clj:136)
        next.jdbc.transaction/fn(transaction.clj:115)
        next.jdbc.protocols$fn__6141$G__6136__6150.invoke(protocols.clj:58)
        next.jdbc$transact.invokeStatic(jdbc.clj:381)
        next.jdbc$transact.invoke(jdbc.clj:373)
        app.rpc.commands.management$sm$clone_template.invokeStatic(management.clj:390)
        app.rpc.commands.management$sm$clone_template.invoke(management.clj:385)
        clojure.lang.AFn.applyToHelper(AFn.java:156)
        clojure.lang.AFn.applyTo(AFn.java:144)
        clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        clojure.lang.RestFn.invoke(RestFn.java:421)
        app.rpc$wrap_dispatch$fn__37004$fn__37005.invoke(rpc.clj:160)
        promesa.exec$wrap_bindings$fn__14953.invoke(exec.cljc:163)
        promesa.util.Supplier.get(util.cljc:34)
        java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
 →  java.nio.file.AccessDeniedException: /opt/data/assets (UnixException.java:90)
    at: sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
        java.nio.file.Files.createDirectory(Files.java:700)
        java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        java.nio.file.Files.createDirectories(Files.java:793)
        datoteka.fs$create_dir.invokeStatic(fs.clj:328)
        datoteka.fs$create_dir.invoke(fs.clj:321)
        datoteka.fs$create_dir.invokeStatic(fs.clj:323)
        datoteka.fs$create_dir.invoke(fs.clj:321)
        app.storage.fs$fn__27684$fn__27687.invoke(fs.clj:58)
        promesa.exec$wrap_bindings$fn__14953.invoke(exec.cljc:163)
        promesa.util.Supplier.get(util.cljc:34)
        java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2023-01-31 23:25:32.404] E app.http.errors - hint="java.nio.file.AccessDeniedException: /opt/data/assets"
TRACE:
 →  java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: /opt/data/assets (CompletableFuture.java:396)
 →  java.nio.file.AccessDeniedException: /opt/data/assets (UnixException.java:90)
DETAIL:
 →  java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: /opt/data/assets (CompletableFuture.java:396)
    at: java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        clojure.core$deref_future.invokeStatic(core.clj:2317)
        clojure.core$deref.invokeStatic(core.clj:2337)
        clojure.core$deref.invoke(core.clj:2323)
        app.rpc.commands.binfile$fn__31845.invokeStatic(binfile.clj:713)
        app.rpc.commands.binfile/fn(binfile.clj:697)
        clojure.lang.MultiFn.invoke(MultiFn.java:229)
        app.rpc.commands.binfile$fn__31742$fn__31744$fn__31745.invoke(binfile.clj:599)
        clojure.core$run_BANG_$fn__8880.invoke(core.clj:7783)
        clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        clojure.core$reduce.invokeStatic(core.clj:6885)
        clojure.core$run_BANG_.invokeStatic(core.clj:7778)
        clojure.core$run_BANG_.invoke(core.clj:7778)
        app.rpc.commands.binfile$fn__31742$fn__31744.invoke(binfile.clj:591)
        next.jdbc.transaction$transact_STAR_.invokeStatic(transaction.clj:72)
        next.jdbc.transaction$transact_STAR_.invoke(transaction.clj:51)
        next.jdbc.transaction$fn__7332.invokeStatic(transaction.clj:136)
        next.jdbc.transaction/fn(transaction.clj:115)
        next.jdbc.protocols$fn__6141$G__6136__6150.invoke(protocols.clj:58)
        next.jdbc$transact.invokeStatic(jdbc.clj:381)
        next.jdbc$transact.invoke(jdbc.clj:373)
        app.rpc.commands.binfile$fn__31742.invokeStatic(binfile.clj:588)
        app.rpc.commands.binfile/fn(binfile.clj:584)
        clojure.lang.MultiFn.invoke(MultiFn.java:229)
        app.rpc.commands.binfile$read_import_BANG_.invokeStatic(binfile.clj:582)
        app.rpc.commands.binfile$read_import_BANG_.invoke(binfile.clj:564)
        app.rpc.commands.binfile$import_BANG_.invokeStatic(binfile.clj:875)
        app.rpc.commands.binfile$import_BANG_.invoke(binfile.clj:866)
        app.rpc.commands.management$clone_template.invokeStatic(management.clj:411)
        app.rpc.commands.management$clone_template.invoke(management.clj:394)
        app.rpc.commands.management$sm$clone_template$fn__42188.invoke(management.clj:392)
        next.jdbc.transaction$transact_STAR_.invokeStatic(transaction.clj:72)
        next.jdbc.transaction$transact_STAR_.invoke(transaction.clj:51)
        next.jdbc.transaction$fn__7332.invokeStatic(transaction.clj:136)
        next.jdbc.transaction/fn(transaction.clj:115)
        next.jdbc.protocols$fn__6141$G__6136__6150.invoke(protocols.clj:58)
        next.jdbc$transact.invokeStatic(jdbc.clj:381)
        next.jdbc$transact.invoke(jdbc.clj:373)
        app.rpc.commands.management$sm$clone_template.invokeStatic(management.clj:390)
        app.rpc.commands.management$sm$clone_template.invoke(management.clj:385)
        clojure.lang.AFn.applyToHelper(AFn.java:156)
        clojure.lang.AFn.applyTo(AFn.java:144)
        clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        clojure.lang.RestFn.invoke(RestFn.java:421)
        app.rpc$wrap_dispatch$fn__37004$fn__37005.invoke(rpc.clj:160)
        promesa.exec$wrap_bindings$fn__14953.invoke(exec.cljc:163)
        promesa.util.Supplier.get(util.cljc:34)
        java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
 →  java.nio.file.AccessDeniedException: /opt/data/assets (UnixException.java:90)
    at: sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
        java.nio.file.Files.createDirectory(Files.java:700)
        java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        java.nio.file.Files.createDirectories(Files.java:793)
        datoteka.fs$create_dir.invokeStatic(fs.clj:328)
        datoteka.fs$create_dir.invoke(fs.clj:321)
        datoteka.fs$create_dir.invokeStatic(fs.clj:323)
        datoteka.fs$create_dir.invoke(fs.clj:321)
        app.storage.fs$fn__27684$fn__27687.invoke(fs.clj:58)
        promesa.exec$wrap_bindings$fn__14953.invoke(exec.cljc:163)
        promesa.util.Supplier.get(util.cljc:34)
        java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
