### ISSUE TITLE
bug: Autosave doesn't recover after an error

### ISSUE THREAD

**Issue by maexrakete** [uxbox/uxbox#3027]
### Steps To Reproduce

Probably hard to reproduce. I usually just worked for a while and the orange notification saying "Unsaved Changes" won't go away.

I still can work in the browser, can upload images, etc, but the orange notification won't go away.

Server logs show, that the penpot-frontend was regularly called at `/api/rpc/command/update-file` until it responded with a 408 error-code, from then on the endpoint wasn't called again until reload.

### Expected behavior

1. Penpot should retry saving
2. Penpot should inform me if saving doesn't work 
3. Penpot should allow me to save manually 
4. Penpot could/should keep a local copy of the file I'm working on, so I can reload safely 

### Actual behavior

Penpot doesn't recover, there's no way to manually save

### Desktop (please complete the following information)

- OS: Linux
- Browser: Firefox 108

### Environment (please complete the following information)

- Host: local instance (self-hosted)
- Host-OS: Ubuntu 22.04.2 LTS, 64-bit, 4GB RAM
- Docker version: Docker version 23.0.1, build a5ee5b1

Docker-Images:
penpotapp/frontend:latest@sha256:af4abcfd62d4
penpotapp/backend:latest@sha256:1a24369cc2de
penpotapp/exporter:latest@sha256:01feb7601dfe

Docker-Compose file:

```
---
version: "3.5"

networks:
  penpot:

volumes:
  penpot_postgres_v15:
  penpot_assets:
  penpot_traefik:

services:
  traefik:
    image: traefik:v2.9
    networks:
      - penpot
    command:
      - "--api.insecure=true"
      - "--entryPoints.web.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=<redacted>"
      - "--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json"
    volumes:
      - "penpot_traefik:/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "80:80"
      - "443:443"

penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    ports:
      - 9001:80

    volumes:
      - penpot_assets:/opt/data/assets

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.http-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.http-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.penpot-http.entrypoints=web"
      - "traefik.http.routers.penpot-http.rule=Host(`<redacted>`)"
      - "traefik.http.routers.penpot-http.middlewares=http-redirect"
      - "traefik.http.routers.penpot-https.entrypoints=websecure"
      - "traefik.http.routers.penpot-https.rule=Host(`<redacted>`)"
      - "traefik.http.services.penpot-https.loadbalancer.server.port=80"
      - "traefik.http.routers.penpot-https.tls=true"  
      - "traefik.http.routers.penpot-https.tls.certresolver=letsencrypt"

    environment:
      - PENPOT_FLAGS=disable-login-with-password disable-registration enable-login-with-github

penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always

    volumes:
      - penpot_assets:/opt/data/assets

    depends_on:
      - penpot-postgres
      - penpot-redis

    networks:
      - penpot

    environment:
      - PENPOT_FLAGS=disable-login-with-password disable-registration enable-login-with-github
      - PENPOT_GITHUB_CLIENT_ID=<redacted>
      - PENPOT_GITHUB_CLIENT_SECRET=<redacted>
      - PENPOT_PUBLIC_URI=<redacted>
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=true
      - PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      - PENPOT_SMTP_HOST=penpot-mailcatch
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_USERNAME=
      - PENPOT_SMTP_PASSWORD=
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false

 penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - penpot

    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT

    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data

    networks:
      - penpot

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot

  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - penpot
```

### Additional context

I'm not entirely sure, if this wasn't caused by some wonky behavior of my Firefox but nonetheless it was pretty frustrating, because I lost 2 hours of work and I wished Penpot would've supported me more in resolving this issue. 

When working, I wasn't really focusing on the save indicator, because it basically changes all the time, so it wasn't really apparent to me, that it got stuck. It also doesn't show a timestamp of the last successful save, which could've been helpful to realize a bit earlier, that there's a problem.

While trying to understand what's going on, I had a look at the project overview, and there it says the last changes were `4 minutes` ago, but I think that was the last time I uploaded an image, not the last time the actual file was saved.

I will try to have a closer look next time I'm using Penpot if I can find additional info, what the actual problem was. If there are other things, I can help you with, please let me know.

Cheers!
