### ISSUE TITLE
bug: LDAP authentication only accepts email, not username

### ISSUE THREAD

**Issue by ProtossGP32** [uxbox/uxbox#3181]
### Steps To Reproduce

1. Configure the `docker-compose.yml` to enable LDAP authentication. Change the user query to only accept usenames
```
#PENPOT_LDAP_USER_QUERY=(&(|(uid=:username)(mail=:username))(memberOf=cn=penpot,ou=groups,dc=my-domain,dc=com))
PENPOT_LDAP_USER_QUERY="(uid=:username)"
```
2. Disable either registration and login with password in both frontend and backend
```
# Frontend
- PENPOT_FLAGS=disable-registration disable-login-with-password enable-login-with-ldap
# Backend
- PENPOT_FLAGS=disable-registration disable-login-with-password disable-email-verification enable-smtp enable-prepl-server enable-login-with-ldap disable-secure-session-cookies
```
4. Deploy a Penpot docker image using the official `docker-compose.yml`

### Expected behavior

The frontend login page should allow the user to input a username.

### Actual behavior

Instead, the frontend login page still expects an email as the only acceptable input:

### Screenshots or video

![image](https://user-images.githubusercontent.com/19353116/235452662-b7d771d9-5fb1-4221-875d-1a794f5a45b9.png)

### Desktop (please complete the following information)

- OS: Debian bullseye
- Web browser: Firefox 102.6.0esr (64 bits), Google Chrome (stable) 111.0.5563.110

### Environment (please complete the following information)

- OS version: Ubuntu Cloud 20.04.5 LTS
- Docker compose file:
```
---
version: "3.5"
networks:
  penpot:
volumes:
  penpot_postgres_v15:
  penpot_assets:
services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    ports:
      - 9001:80
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot
    labels:
      - "traefik.enable=true"
    environment:
      - PENPOT_FLAGS=disable-registration disable-login-with-password enable-login-with-ldap
  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-postgres
      - penpot-redis
    networks:
      - penpot
    environment:
      - PENPOT_FLAGS=disable-registration disable-login-with-password disable-email-verification enable-smtp enable-prepl-server enable-login-with-ldap disable-secure-session-cookies
      - PENPOT_PUBLIC_URI=http://localhost:9001
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=true
      - PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      - PENPOT_SMTP_HOST=penpot-mailcatch
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_USERNAME=
      - PENPOT_SMTP_PASSWORD=
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false
      - PENPOT_LDAP_HOST=${PENPOT_LDAP_HOST}
      - PENPOT_LDAP_PORT=${PENPOT_LDAP_PORT}
      - PENPOT_LDAP_SSL=${PENPOT_LDAP_SSL}
      - PENPOT_LDAP_STARTTLS=${PENPOT_LDAP_STARTTLS}
      - PENPOT_LDAP_BASE_DN=${PENPOT_LDAP_BASE_DN}
      - PENPOT_LDAP_BIND_DN=${PENPOT_LDAP_BIND_DN}
      - PENPOT_LDAP_BIND_PASSWORD=${PENPOT_LDAP_BIND_PASSWORD}
      - PENPOT_LDAP_USER_QUERY=${PENPOT_LDAP_USER_QUERY}
      - PENPOT_LDAP_ATTRS_USERNAME=${PENPOT_LDAP_ATTRS_USERNAME}
      - PENPOT_LDAP_ATTRS_FULLNAME=${PENPOT_LDAP_ATTRS_FULLNAME}
  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - penpot
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0
  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT
    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data
    networks:
      - penpot
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot
  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot
  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - penpot
```

### Additional context

Nothing special, LDAP works fine when configuring the user query to accept email field as username
