### ISSUE TITLE
feature: serve penpot un subpath

### ISSUE THREAD

**Issue by n-arakawa** [uxbox/uxbox#3194]
### Is your feature request related to a problem? Please describe.

I’m running Penpot behind a reverse proxy with subpath (i.e 'https://my-host/penpot' ).
Setting `PENPOT_PUBLIC_URI` in  docker-compose.penpot.env does'nt reflect to `public-uri`(defined in frontend/src/app/config.cljs)

### Describe the solution you'd like.

Hope to add penpotPublicURI setting according to 'PENPOT_PUBLIC_URI' by 
nginx-entrypoint.sh

`var penpotPublicURI="<Value of PENPOT_PUBLIC_URI>";`

**Comment by niwinz** [comment]
Question:  why do you need to set it? I mean, when it is not set on frontend it uses the default origin/href. Ourselves don't use it on our SAAS.

**Comment by n-arakawa** [comment]
I believe you are referring to the following code for what happens when "penpotPublicURI" has no value.

frontend/src/app/config.cljs
```
(def public-uri
  (atom
   (normalize-uri (or (obj/get global "penpotPublicURI")
                      (.-origin ^js location)))))
```

However, this code doesn't seem to take subpaths into account.

The 'public-uri' is set to 'https://my-host/' even though the penpot's access URL is 'https://my-host/penpot'

My current workaround  is:

docker/images/files/nginx-entrypoint.sh(`entrypoint.sh` in docker image)
```
  if [ "$PENPOT_PUBLIC_URI" != "http://localhost:9001" ]; then
      printf "var penpotPublicURI='%s';\\n" "$PENPOT_PUBLIC_URI" >> "$1"
  fi
```

**Comment by niwinz** [comment]
Oh, I understand, penpot right now is not working correctly on subpath, so setting it on config.js will not make it work correctly anyway. This is something that some people have asked us for, and we have had it working for some versions, but right now it is buggy and we consider it as not supported.

In any case, soon we will have a conversation about on-premise features and I will raise this issue to talk about on the team.

**Comment by n-arakawa** [comment]
Thank you for the title change!

**Comment by JacobDB** [comment]
I'd love to see this feature; I prefer to host my web applications under one subdomain, mostly for ease of SSL management.

**Comment by cccs-rs** [comment]
My team and I would also be interested in this feature so we can attach Penpot to our staging cluster (under `/penpot`) where we also host our development app.

**Comment by bartvdbraak** [comment]
Has there been any movement on this issue? We would like to host our Penpot instance on a subpath like `/projects`.

I tried to do the following in the Docker Compose

```
...
x-uri: &penpot-public-uri
  PENPOT_PUBLIC_URI: https://{{ penpot_domain }}/projects
..
  penpot-frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.penpot-http.rule=Host(`{{ penpot_domain }}`) && PathPrefix(`/projects`)"
      - "traefik.http.routers.penpot-http.entrypoints=web"
      - "traefik.http.routers.penpot-http.middlewares=https-redirect"
      - "traefik.http.routers.penpot-https.rule=Host(`{{ penpot_domain }}`) && PathPrefix(`/projects`)"
      - "traefik.http.routers.penpot-https.entrypoints=websecure"
      - "traefik.http.routers.penpot-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.penpot-https.tls=true"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
    environment:
      << : [*penpot-flags, *penpot-http-body-size]
...
```

The frontend does load on `/projects` but with a server error.

See the following frontend logs:

```
172.18.0.4 - - [24/Oct/2025:20:29:23 +0000] "GET /ws/notifications?session-id=<redacted> HTTP/1.1" 502 150 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:139.0) Gecko/20100101 Firefox/139.0"
2025/10/24 20:29:23 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.4, server: _, request: "GET /ws/notifications?session-id=<redacted> HTTP/1.1", upstream: "http://172.18.0.5:6060/ws/notifications?session-id=<redacted>", host: "<redacted>"
172.18.0.4 - - [24/Oct/2025:20:30:09 +0000] "GET /projects HTTP/1.1" 200 762458 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:139.0) Gecko/20100101 Firefox/139.0"
```

**Comment by mstred** [comment]
I think that the [penpot/frontend](https://github.com/penpot/penpot/blob/develop/frontend) application is supposed to have a [`<base>` HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/base#examples) inside its generated `index.html` file in order to enable that feature.
However, I have no clue on how that should be implemented, let alone parameterized by runtime options, as the `index.html` file comes from a templated [`resources/templates/index.mustache`](https://github.com/penpot/penpot/blob/develop/frontend/resources/templates/index.mustache) file and this should probably be rendered in build time.

A workaround that comes to my head is something in the likes of "injecting" that element to the already-built `index.html` file provided by the container image through an entrypoint script. But it doesn't seem quite dependable.

**Comment by mstred** [comment]
I've just found out this seems to be a duplicate of #1380. Then again, I'm still trying to figure out a way on how to deal with it.
I had a little bit of success trying to put that idea of mine to work, but it wasn't enough to mark that as solved.
Besides the entrypoint changes to inject a `<base href="/penpot/">` element, I had to do some tricks in the traefik labels to strip the path prefix. Here's how I did:
1. Add the following line to the content of the `entrypoint.sh` file (copied and bind-mounted to the `penpot-frontend` container):
```shell
sed -i 's|<head>|<head>\n    <base href="/penpot/">|' /var/www/app/index.html
```

2. Besides uncommenting all Traefik-related lines from the [original compose file](https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml), these were the ones that made things happen:
```yaml
    # ...
    image: traefik:v3.6 # can't seem to understand, but only v3.6 works when running docker engine from WSL2
    # ...
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro # already mentioned in the previous step
    # ...
    labels:
      - "traefik.http.routers.penpot-https.rule=PathPrefix(`/penpot`)"
      - "traefik.http.routers.penpot-https.middlewares=penpot-stripprefix"
      - "traefik.http.middlewares.penpot-stripprefix.stripprefix.prefixes=/penpot"
```

It looked promising, but when the app started to do some requests to the backend, frustration came along:

<img width="1920" height="1032" alt="Image" src="https://github.com/user-attachments/assets/e33c03a6-ebee-4b56-bc41-493549cf9ac9" />

I suppose some changes might be required to the actual frontend code so that the backend calls can be set to a different path instead of the root one.
