### ISSUE TITLE
Can I map the data to the host for storage, using volumes

### ISSUE THREAD

**Issue by ghostxiu** [uxbox/uxbox#3463]
Just like this:
```
  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT

    volumes:
      - /var/data/postgresql/data:/var/lib/postgresql/data
```
