### ISSUE TITLE
bug: Cannot edit z-index on any Flex elements

### ISSUE THREAD

**Issue by jackinh** [uxbox/uxbox#3640]
### Steps To Reproduce

1. Create a new file.
2. Add a board with a flex layout.
3. Add some child elements (of any kind).
4. Notice that you can only edit the z-index if positioned absolutely
5. (BONUS) If you remove the `disabled=""` attribute on the input HTML element then the z-index can be edited for statically positioned elements

### Expected behavior

The input box should be enabled in order to reposition my elements. They are overlapping and if I hack the UI to remove the `disabled=""` attribute, then the z-index value is accepted and works as intended.

### Actual behavior

The input element for the z-index is always disabled for statically positioned elements.

### Screenshots or video

https://github.com/penpot/penpot/assets/77571835/4bc12e2e-851e-4c9a-abdb-5768b9d14866

### Desktop (please complete the following information)

- Windows 10 22H2 (19045.3448)
- Firefox 117.0.1 (64-bit)
- Google Chrome 117.0.5938.88 (64-bit)

### Environment (please complete the following information)

- Self-hosted (v1.19)
- Ubuntu Server 22.04.3
- Docker CE 24.0.6, build 1a79695
- Docker Compose 2.21.0
- Image `penpotapp/frontend:latest`

Docker compose file:
```yaml
version: '3'

services:
  penpot-frontend:
    container_name: penpot-frontend
    image: "penpotapp/frontend:latest"
    restart: unless-stopped
    networks:
      private: {}
    ports:
      - 9001:80
    volumes:
      - penpot-assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    environment:
      - PENPOT_FLAGS=disable-registration disable-login-with-password enable-login-with-oidc
  penpot-backend:
    container_name: penpot-backend
    image: "penpotapp/backend:latest"
    restart: unless-stopped
    networks:
      private: {}
    depends_on:
      - penpot-postgres
      - penpot-redis
    volumes:
      - penpot-assets:/opt/data/assets
    environment:
      - PENPOT_FLAGS=disable-registration disable-login-with-password enable-login-with-oidc enable-prepl-server disable-email-verification
      - PENPOT_SECRET_KEY=<omitted>
      - PENPOT_PREPL_HOST=0.0.0.0
      - PENPOT_PUBLIC_URI=<omitted>
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=<omitted>
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=false
      - PENPOT_OIDC_CLIENT_ID=penpot
      - PENPOT_OIDC_BASE_URI=<omitted>
      - PENPOT_OIDC_CLIENT_SECRET=<omitted>
  penpot-exporter:
    container_name: penpot-exporter
    image: "penpotapp/exporter:latest"
    restart: unless-stopped
    networks:
      private: {}
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend

      ## Redis is used for the websockets notifications.
      - PENPOT_REDIS_URI=redis://penpot-redis/0
  penpot-postgres:
    container_name: penpot-postgres
    image: "postgres:15"
    restart: unless-stopped
    networks:
      private: {}
    secrets:
      - penpot-postgres-password-secret
    stop_signal: SIGINT
    volumes:
      - penpot-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD_FILE=/run/secrets/penpot-postgres-password-secret
  penpot-redis:
    container_name: penpot-redis
    image: redis:7
    restart: unless-stopped
    networks:
      private: {}
```
