### ISSUE TITLE
bug: log in error

### ISSUE THREAD

**Issue by XIYO** [uxbox/uxbox#3735]
### Steps To Reproduce

my server is 192.168.1.10

**SERVER**:

```bash
mkdir ~/penpot
cd ~/penpot
wget https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml

# add penpot-frontend flags
# and penpot-backend flags
#
#  added `disable-secure-session-cookies`
# PENPOT_FLAGS=enable-registration enable-login-with-password disable-secure-session-cookies

docker compose -p penpot -f docker-compose.yaml up -d

docker exec -ti penpot-penpot-backend-1 python3 ./manage.py create-profile
Email: test@test.com
Fullname: test
Password: test
Created: test@test.com / 83aa67b3-9179-80e9-8003-54f73d53a5cf
```

**CLIENT**:
1. open edge
2. url : http://myMacMini:9001
3. login

### Expected behavior

can login

### Actual behavior

cant login

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/27078637/3027364f-066e-4815-a701-8e1ba59b52dd)

### Desktop (please complete the following information)

- Windows 11
- Edge 118

### Environment (please complete the following information)

- MacMini Intel, sonoma

```bash
docker -v
Docker version 24.0.6, build ed223bc

docker compose version
Docker Compose version v2.22.0-desktop.2
```

### Additional context

Hello,

I'm using a translator to write this message, so please excuse any awkward phrasing.

Here's what I've done:

I added the `disable-secure-session-cookies` option to the frontend settings. Then, I used the command to create a new account:
```
docker exec -ti penpot-penpot-backend-1 python3 ./manage.py create-profile
```
I've also accessed it from another PC on the local network. I'm encountering the same login error whether I connect to the server using 127.0.0.1:9001 or localhost:9001.

I'm confused about where exactly the `disable-secure-session-cookies` option should be configured. The [Penpot technical guide](https://help.penpot.app/technical-guide/configuration/#advanced-configuration) just mentions it under "other flags." Is it an option for the frontend or the backend?

**Comment by azagaya** [comment]
I'm having the same issue. Any workarround?

**Comment by XIYO** [comment]
현재 서버가 고장나서 확인이 불가능합니다.
마지막으로 재생했던, `docker-compose.yml`을 공유드립니다.

제 기억으로는 메뉴얼에서 아래의 옵션으로 로그인을 제어했습니다.(메뉴얼이 상세하지 않아, 프론트 백엔드 둘 다 주었습니다.현재의 로그인 옵션은 깃랩에 연동되어있습니다.)

`- PENPOT_FLAGS=disable-registration disable-email-verification enable-smtp enable-prepl-server enable-login-with-gitlab disable-login-with-password`


```
---
version: "3.5"

networks:
  traefik-public:
    external: true

volumes:
  penpot_assets:
  # penpot_minio:

services:

  penpot-frontend:
    container_name: penpot-frontend
    image: "penpotapp/frontend:latest"
    restart: always

    volumes:
      - penpot_assets:/opt/data/assets

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - traefik-public

    labels:
      - "traefik.enable=true"

      ## HTTP: example of labels for the case if you are going to expose penpot to the
      ## internet using only HTTP (without HTTPS) with traefik

      - "traefik.http.routers.penpot-http.entrypoints=web"
      - "traefik.http.routers.penpot-http.rule=Host(`penpot.xiyo.dev`)"
      - "traefik.http.services.penpot-http.loadbalancer.server.port=80"

      ## HTTPS: example of labels for the case if you are going to expose penpot to the
      ## internet using with HTTPS using traefik

      # - "traefik.http.middlewares.http-redirect.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.http-redirect.redirectscheme.permanent=true"
      # - "traefik.http.routers.penpot-http.entrypoints=web"
      # - "traefik.http.routers.penpot-http.rule=Host(`<DOMAIN_NAME>`)"
      # - "traefik.http.routers.penpot-http.middlewares=http-redirect"
      # - "traefik.http.routers.penpot-https.entrypoints=websecure"
      # - "traefik.http.routers.penpot-https.rule=Host(`<DOMAIN_NAME>`)"
      # - "traefik.http.services.penpot-https.loadbalancer.server.port=80"
      # - "traefik.http.routers.penpot-https.tls=true"
      # - "traefik.http.routers.penpot-https.tls.certresolver=letsencrypt"

    ## Configuration envronment variables for frontend the container. In this case this
    ## container only needs the `PENPOT_FLAGS`. This environment variable is shared with
    ## other services but not all flags are relevant to all services.

    environment:
      ## Relevant flags for frontend:
      ## - demo-users
      ## - login-with-github
      ## - login-with-gitlab
      ## - login-with-google
      ## - login-with-ldap
      ## - login-with-oidc
      ## - login-with-password
      ## - registration
      ## - webhooks
      ##
      ## You can read more about all available flags on:
      ## https://help.penpot.app/technical-guide/configuration/#advanced-configuration

      - PENPOT_FLAGS=disable-registration disable-secure-session-cookies enable-login-with-gitlab disable-login-with-password

  penpot-backend:
    container_name: penpot-backend
    image: "penpotapp/backend:latest"
    restart: always

    volumes:
      - penpot_assets:/opt/data/assets

    networks:
      - traefik-public

    ## Configuration envronment variables for backend the
    ## container.

    environment:

      ## Relevant flags for backend:
      ## - demo-users
      ## - email-verification
      ## - log-emails
      ## - log-invitation-tokens
      ## - login-with-github
      ## - login-with-gitlab
      ## - login-with-google
      ## - login-with-ldap
      ## - login-with-oidc
      ## - login-with-password
      ## - registration
      ## - secure-session-cookies
      ## - smtp
      ## - smtp-debug
      ## - telemetry
      ## - webhooks
      ## - prepl-server
      ##
      ## You can read more about all available flags and other
      ## environment variables for the backend here:
      ## https://help.penpot.app/technical-guide/configuration/#advanced-configuration

      - PENPOT_FLAGS=disable-registration disable-email-verification enable-smtp enable-prepl-server enable-login-with-gitlab disable-login-with-password

      ## Penpot SECRET KEY. It serves as a master key from which other keys for subsystems
      ## (eg http sessions, or invitations) are derived.
      ##
      ## If you leve it commented, all created sessions and invitations will
      ## become invalid on container restart.
      ##
      ## If you going to uncomment this, we recommend use here a trully randomly generated
      ## 512 bits base64 encoded string.  You can generate one with:
      ##
      ## python3 -c "import secrets; print(secrets.token_urlsafe(64))"

      # - PENPOT_SECRET_KEY=my-insecure-key

      ## The PREPL host. Mainly used for external programatic access to penpot backend
      ## (example: admin). By default it listen on `localhost` but if you are going to use
      ## the `admin`, you will need to uncomment this and set the host to `0.0.0.0`.

      # - PENPOT_PREPL_HOST=0.0.0.0

      ## Public URI. If you are going to expose this instance to the internet and use it
      ## under different domain than 'localhost', you will need to adjust it to the final
      ## domain.
      ##
      ## Consider using traefik and set the 'disable-secure-session-cookies' if you are
      ## not going to serve penpot under HTTPS.

      - PENPOT_PUBLIC_URI=https://penpot.xiyo.dev

      ## Database connection parameters. Don't touch them unless you are using custom
      ## postgresql connection parameters.

      - PENPOT_DATABASE_URI=postgresql://XIYOsMini/penpot
      - PENPOT_DATABASE_USERNAME=secret
      - PENPOT_DATABASE_PASSWORD=secret

      ## Redis is used for the websockets notifications. Don't touch unless the redis
      ## container has different parameters or different name.

      - PENPOT_REDIS_URI=redis://XIYOsMini/1

      ## Default configuration for assets storage: using filesystem based with all files
      ## stored in a docker volume.

      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets

      ## Also can be configured to to use a S3 compatible storage
      ## service like MiniIO. Look below for minio service setup.

      # - AWS_ACCESS_KEY_ID=<KEY_ID>
      # - AWS_SECRET_ACCESS_KEY=<ACCESS_KEY>
      # - PENPOT_ASSETS_STORAGE_BACKEND=assets-s3
      # - PENPOT_STORAGE_ASSETS_S3_ENDPOINT=http://penpot-minio:9000
      # - PENPOT_STORAGE_ASSETS_S3_BUCKET=<BUKET_NAME>

      ## Telemetry. When enabled, a periodical process will send anonymous data about this
      ## instance. Telemetry data will enable us to learn on how the application is used,
      ## based on real scenarios. If you want to help us, please leave it enabled. You can
      ## audit what data we send with the code available on github

      - PENPOT_TELEMETRY_ENABLED=true

      ## Example SMTP/Email configuration. By default, emails are sent to the mailcatch
      ## service, but for production usage is recommended to setup a real SMTP
      ## provider. Emails are used to confirm user registrations & invitations. Look below
      ## how mailcatch service is configured.

      - PENPOT_SMTP_DEFAULT_FROM=Penpot <no-reply@xiyo.dev>
      - PENPOT_SMTP_DEFAULT_REPLY_TO=Penpot <no-reply@xiyo.dev>
      - PENPOT_SMTP_HOST=smtp.mail.some.com
      - PENPOT_SMTP_PORT=587
      - PENPOT_SMTP_USERNAME=my@email.com
      - PENPOT_SMTP_PASSWORD=secret
      - PENPOT_SMTP_TLS=true
      - PENPOT_SMTP_SSL=false

      ## GITLAB
      
      - PENPOT_GITLAB_BASE_URI=https://gitlab.xiyo.dev
      - PENPOT_GITLAB_CLIENT_ID=secret
      - PENPOT_GITLAB_CLIENT_SECRET=secret

  penpot-exporter:
    container_name: penpot-exporter
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - traefik-public

    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend

      ## Redis is used for the websockets notifications.
      - PENPOT_REDIS_URI=redis://XIYOsMini/1

```
