### ISSUE TITLE
bug: Backend not starting up, reporting wrong CPU usage

### ISSUE THREAD

**Issue by TheEmeraldChickn** [uxbox/uxbox#3739]
### Steps To Reproduce

1. Start a new project
2. Add the docker-compose yaml
3. Start the container
```
version: "3.5"
services:
  redis:
    image: redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redispass
    container_name: Penpot-REDIS
    hostname: penpot-redis
    mem_limit: 256m
    mem_reservation: 50m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: 1026:100
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - /volume1/docker/penpot/redis:/data:rw
    environment:
      TZ: Europe/Amsterdam
    restart: on-failure:5

  db:
    image: postgres
    container_name: Penpot-DB
    hostname: penpot-db
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "penpot", "-U", "penpotuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/penpot/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: penpot
      POSTGRES_USER: penpotuser
      POSTGRES_PASSWORD: penpotpass
      POSTGRES_INITDB_ARGS: --data-checksums
    restart: on-failure:5

  penpot-exporter:
    image: penpotapp/exporter:main
    container_name: Penpot-EXPORTER
    hostname: penpot-exporter
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    environment:
      PENPOT_PUBLIC_URI: localhost:9010
      PENPOT_REDIS_URI: redis://:redispass@penpot-redis/0
    restart: on-failure:5

  penpot-backend:
    image: penpotapp/backend:main
    container_name: Penpot-BACKEND
    hostname: penpot-backend
    mem_limit: 3g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume1/docker/penpot/assets:/opt/data/assets:rw
    environment:
      PENPOT_FLAGS: enable-registration enable-login-with-password disable-email-verification enable-prepl-server enable-smtp
      PENPOT_SECRET_KEY: theecretkey
      ## The PREPL host. Mainly used for external programatic access to penpot backend
      ## (example: admin). By default it listen on `localhost` but if you are going to use
      ## the `admin`, you will need to uncomment this and set the host to `0.0.0.0`.
      # - PENPOT_PREPL_HOST=0.0.0.0
      PENPOT_PUBLIC_URI: localhost:9010
      PENPOT_DATABASE_URI: postgresql://penpot-db/penpot
      PENPOT_DATABASE_USERNAME: penpotuser
      PENPOT_DATABASE_PASSWORD: penpotpass
      PENPOT_REDIS_URI: redis://:redispass@penpot-redis/0
      PENPOT_ASSETS_STORAGE_BACKEND: assets-fs
      PENPOT_STORAGE_ASSETS_FS_DIRECTORY: /opt/data/assets
      PENPOT_TELEMETRY_ENABLED: false
      PENPOT_SMTP_HOST: smtp.mydomain.com
      PENPOT_SMTP_DEFAULT_FROM: my@email.com
      PENPOT_SMTP_DEFAULT_REPLY_TO: my@email.com
      PENPOT_SMTP_PORT: 587
      PENPOT_SMTP_USERNAME: my@email.com
      PENPOT_SMTP_PASSWORD: myemailpassword
      PENPOT_SMTP_TLS: true
      PENPOT_SMTP_SSL: false
    restart: on-failure:5
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  penpot-frontend:
    image: penpotapp/frontend:main
    container_name: Penpot-FRONTEND
    hostname: penpot-frontend
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 9010:80
    volumes:
      - /volume1/docker/penpot/assets:/opt/data/assets:rw
    environment:
      PENPOT_FLAGS: enable-registration enable-login-with-password
    restart: on-failure:5
    depends_on:
      penpot-backend:
        condition: service_started
      penpot-exporter:
        condition: service_started
```

### Expected behavior

For the containers to start, with the frontend showing the login screen.

### Actual behavior

All containers start and stay alive, besides the backend one.

Reaching the frontend gives the 'Internal Error' message. 

The only logs the backend displays are these.
```
[2023-10-30 17:30:51.027] I app.migrations - hint="running migrations", module=:app.migrations/migrations
[2023-10-30 17:30:50.985] I app.db - hint="initialize connection pool", name="main", uri="postgresql://penpot-db/penpot", read-only=false, with-credentials=true, min-size=0, max-size=60
2023/10/30 18:30:50 | stdout | [2023-10-30 17:30:50.953] I app.metrics - action="initialize metrics"
2023/10/30 18:30:36 | stdout | INFO StatusConsoleListener Registered Log4j as the java.util.logging.LogManager.
2023/10/30 18:30:20 | stderr | + exec /opt/jdk/bin/java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlog4j2.configurationFile=log4j2.xml -XX:-OmitStackTraceInFastThrow --enable-preview -jar penpot.jar -m app.main
```

### Environment (please complete the following information)

Device Specs
- Synology DS923+
- DSM 7.2-64570 Update 3
- 20GB Ram (4 + 16)
- Using Container Manager version 20.10.23-1437

### Frontend Stack Trace

```console
Internal Error
```

### Backend Stack Trace

```console
[2023-10-30 17:30:51.027] I app.migrations - hint="running migrations", module=:app.migrations/migrations
[2023-10-30 17:30:50.985] I app.db - hint="initialize connection pool", name="main", uri="postgresql://penpot-db/penpot", read-only=false, with-credentials=true, min-size=0, max-size=60
2023/10/30 18:30:50 | stdout | [2023-10-30 17:30:50.953] I app.metrics - action="initialize metrics"
2023/10/30 18:30:36 | stdout | INFO StatusConsoleListener Registered Log4j as the java.util.logging.LogManager.
2023/10/30 18:30:20 | stderr | + exec /opt/jdk/bin/java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlog4j2.configurationFile=log4j2.xml -XX:-OmitStackTraceInFastThrow --enable-preview -jar penpot.jar -m app.main
```

### Additional context

I've tried it on both my main Synology unit, as well as a clean version of Virtual DSM, both yielding the exact same result.
Weirdly enough, CPU usage for the penpot-backend container reports anything between -300% and +400%, while the other penpot containers are between 0 and 0,5%.
