### ISSUE TITLE
bug: Live Editing (multiplayer) not working correctly

### ISSUE THREAD

**Issue by MrMK0R** [uxbox/uxbox#3788]
### Steps To Reproduce

1. Login
2. Create new board
3. Create Team
4. Add board to Team
5. Invite another user
6. Both open to edit

### Expected behavior

Both users can't open the same document and edit live with each other. The page has to be refreshed to see any changes the other person has made. If the new user changes content, and the old user saves, the new content gets written over.

### Actual behavior

Have to consistently refresh the page to see any changes.

### Desktop (please complete the following information)

- Desktop (Edge Latest)
- Desktop Chrome (Latest)
- Desktop Firefox DE (Latest)

### Smartphone (please complete the following information)

N/A

### Environment (please complete the following information)

Server:
Ubuntu 22.04
4 Core, 6GB Ram.

Docker Compose

### Frontend Stack Trace

```console
penpot-penpot-frontend-1  | 2023/11/10 01:02:48 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: _, request: "GET /ws/notifications?session-id=61444025-6c04-80da-8003-68f3cf864400 HTTP/1.1", upstream: "http://172.24.0.6:6060/ws/notifications?session-id=61444025-6c04-80da-8003-68f3cf864400", host: "design.website.ca"
penpot-penpot-frontend-1  | 2023/11/10 01:02:54 [error] 12#12: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: _, request: "GET /api/rpc/command/get-profile HTTP/1.1", upstream: "http://172.24.0.6:6060/api/rpc/command/get-profile", host: "design.website.ca"
```

### Backend Stack Trace

```console
No errors are displayed in the backend.
```

**Comment by superalex** [comment]
Hi @MrMK0R 

This one sounds like some kind of configuration issue, I've just created a new docker installation base on this dockerfile -> https://github.com/penpot/penpot/blob/develop/docker/devenv/docker-compose.yaml and multiplayer edition works correctly. Feel free to reopen the issue if you have more info.

Thank you very much! :)

**Comment by MrMK0R** [comment]
Hey @superalex,

I have everything works still besides any multi-editor / multi-player functions. I've attached my docker-compose.yaml file incase I may have missed something, but I don't believe I have. I checked the docker-compose that you sent, and there are a few sevices that I am not using which I am wondering could be the problem.

Thanks for the help!

```yaml
networks:
  penpot:

volumes:
  penpot_postgres_v15:
  penpot_assets:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    ports:
      - 9001:80

    volumes:
      - ./penpot_assets:/opt/data/assets

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

    environment:
      - PENPOT_FLAGS=disable-registration enable-login-with-password

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always

    volumes:
      - ./penpot_assets:/opt/data/assets

    depends_on:
      - penpot-postgres
      - penpot-redis

    networks:
      - penpot

    environment:

      - PENPOT_FLAGS=disable-dashboard-templates-section disable-onboarding enable-registration enable-login-with-password enable-secure-session-cookies enable-email-verification enable-smtp enable-prepl-server
      - PENPOT_SECRET_KEY=**************
      - PENPOT_PUBLIC_URI=https://design.**************.**************
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - AWS_ACCESS_KEY_ID=**************
      - AWS_SECRET_ACCESS_KEY=**************
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-s3
      - PENPOT_STORAGE_ASSETS_S3_REGION=**************
      - PENPOT_STORAGE_ASSETS_S3_BUCKET=**************
      - PENPOT_STORAGE_ASSETS_S3_ENDPOINT=**************
      - PENPOT_TELEMETRY_ENABLED=true
      - PENPOT_SMTP_DEFAULT_FROM=**************
      - PENPOT_SMTP_DEFAULT_REPLY_TO=**************
      - PENPOT_SMTP_HOST=**************
      - PENPOT_SMTP_PORT=465
      - PENPOT_SMTP_USERNAME=**************
      - PENPOT_SMTP_PASSWORD=**************
      - PENPOT_SMTP_TLS=true
      - PENPOT_SMTP_SSL=true

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - penpot

    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT

    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data

    networks:
      - penpot

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot

  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - penpot
```
