### ISSUE TITLE
feature: Prepend `system-ui` to ui font stack

### ISSUE THREAD

**Issue by owzim** [uxbox/uxbox#4335]
### Is your feature request related to a problem? Please describe.

I understand the need for branding, but `worksans` is not close to being a good fit as a UI font.

Please consider user preference and accessibility to be more important than branding

see: https://github.com/system-fonts/modern-font-stacks?tab=readme-ov-file#system-ui

> System UI fonts are those native to the operating system interface. They are highly legible and easy to read at small sizes, contains many font weights, and are ideal for UI elements.
 

### Describe the solution you'd like.

Instead of this:

```css
.any-selector-that-uses-the-fontstack {
  font-family: "worksans", sans-serif
}
```

use this:

```css
.any-selector-that-uses-the-fontstack {
  font-family: system-ui, "worksans", sans-serif
}
```
