### ISSUE TITLE
bug: 400 (Bad Request)

### ISSUE THREAD

**Issue by DeAlexPesh** [uxbox/uxbox#4424]
#### prepare
```
sudo mkdir -p /app/compose/penpot
sudo mkdir -p /app_base/penpot/{assets,db,redis}
```

#### .env

```
sudo nano /app/compose/penpot/.env
TZ=Asia/Yekaterinburg
PENPOT_FLAGS=disable-registration enable-webhooks disable-demo-users enable-login enable-login-with-password enable-login-with-gitlab
PENPOT_FLAGS_FRONT=${PENPOT_FLAGS}
PENPOT_FLAGS_BACK=${PENPOT_FLAGS} enable-prepl-server disable-telemetry enable-smtp disable-email-verification
PENPOT_PUBLIC_URI=https://penpot.ente-ltd.ru
PENPOT_SECRET_KEY=00000000000000000000000000000000000000000000000000000000
# DB
POSTGRES_DB=penpot
POSTGRES_USER=penpot
POSTGRES_PASSWORD=12345678
PENPOT_DATABASE_URI=postgresql://db/${POSTGRES_DB}
# SMTP
PENPOT_SMTP_DEFAULT_FROM=me@domain.ru
PENPOT_SMTP_DEFAULT_REPLY_TO=admin@domain.ru
PENPOT_SMTP_HOST=smtp.domain.ru
PENPOT_SMTP_PORT=465
PENPOT_SMTP_USERNAME=me@domain.ru
PENPOT_SMTP_PASSWORD=12345678
PENPOT_SMTP_TLS=true
PENPOT_SMTP_SSL=false
# STORAGE
PENPOT_ASSETS_STORAGE_BACKEND=assets-fs # assets-s3
PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
# REDIS
PENPOT_REDIS_URI=redis://redis/0
# Gitlab
# https://domain.ru/api/auth/oauth/gitlab/callback
PENPOT_GITLAB_BASE_URI=https://git.domain.ru
PENPOT_GITLAB_CLIENT_ID=000000000000000000000000000000000000000000000000000
PENPOT_GITLAB_CLIENT_SECRET=0000000000000000000000000000000000000000000000000000000000000
```

#### docker-compose.yml
```
sudo bash -c 'cat <<EOT > /app/compose/penpot/penpot.yml
version: "3"
name: penpot

x-penpot-depend: &penpot-depend
 networks:
  - penpot
 logging:
  driver: "json-file"
  options:
   max-size: "200k"
   max-file: "5"
 restart: always

services:
 penpot-frontend:
  image: penpotapp/frontend:latest
  container_name: "penpot-frontend"
  ports:
   - "0.0.0.0:9001:80"
  environment:
   - TZ=\${TZ}
   - PENPOT_FLAGS=\${PENPOT_FLAGS_FRONT}
  volumes:
   - /app_base/penpot/assets:/opt/data/assets
  depends_on:
   penpot-backend:
    condition: service_started
   penpot-exporter:
    condition: service_started
  <<: [ *penpot-depend ]

 penpot-backend:
  image: penpotapp/backend:latest
  container_name: "penpot-backend"
  environment:
   - TZ=\${TZ}
   - PENPOT_FLAGS=\${PENPOT_FLAGS_BACK}
   - PENPOT_TELEMETRY_ENABLED=false
   - PENPOT_SECRET_KEY=\${PENPOT_SECRET_KEY}
   - PENPOT_PUBLIC_URI=\${PENPOT_PUBLIC_URI}
   - PENPOT_DATABASE_URI=\${PENPOT_DATABASE_URI}
   - PENPOT_DATABASE_USERNAME=\${POSTGRES_USER}
   - PENPOT_DATABASE_PASSWORD=\${POSTGRES_PASSWORD}
   - PENPOT_REDIS_URI=\${PENPOT_REDIS_URI}
   - PENPOT_ASSETS_STORAGE_BACKEND=\${PENPOT_ASSETS_STORAGE_BACKEND}
   - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=\${PENPOT_STORAGE_ASSETS_FS_DIRECTORY}
   - PENPOT_SMTP_DEFAULT_FROM=\${PENPOT_SMTP_DEFAULT_FROM}
   - PENPOT_SMTP_DEFAULT_REPLY_TO=\${PENPOT_SMTP_DEFAULT_REPLY_TO}
   - PENPOT_SMTP_HOST=\${PENPOT_SMTP_HOST}
   - PENPOT_SMTP_PORT=\${PENPOT_SMTP_PORT}
   - PENPOT_SMTP_USERNAME=\${PENPOT_SMTP_USERNAME}
   - PENPOT_SMTP_PASSWORD=\${PENPOT_SMTP_PASSWORD}
   - PENPOT_SMTP_TLS=\${PENPOT_SMTP_TLS}
   - PENPOT_SMTP_SSL=\${PENPOT_SMTP_SSL}
  volumes:
   - "/app_base/penpot/assets:/opt/data/assets"
  depends_on:
   penpot-db:
    condition: service_healthy
   penpot-redis:
    condition: service_started
  links:
   - penpot-db:db
   - penpot-redis:redis
  <<: [ *penpot-depend ]

 penpot-exporter:
  image: penpotapp/exporter:latest
  container_name: "penpot-exporter"
  environment:
   - TZ=\${TZ}
   - PENPOT_PUBLIC_URI=http://penpot-frontend # NO CHANGE!
   - PENPOT_REDIS_URI=\${PENPOT_REDIS_URI}
  depends_on:
   penpot-redis:
    condition: service_started
  links:
   - penpot-redis:redis
  <<: [ *penpot-depend ]

 penpot-db:
  image: postgres:15-alpine
  container_name: "penpot-db"
  environment:
   - POSTGRES_INITDB_ARGS=--data-checksums
   - POSTGRES_DB=\${POSTGRES_DB}
   - POSTGRES_USER=\${POSTGRES_USER}
   - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
   - TZ=\${TZ}
   - PGTZ=\${TZ}
  volumes:
   - "/app_base/penpot/db:/var/lib/postgresql/data"
  healthcheck:
   test: [ "CMD-SHELL", "pg_isready -d \$\${POSTGRES_DB} -U \$\${POSTGRES_USER} --quiet" ]
   start_period: 20s
   interval: 2s
   timeout: 15s
   retries: 10
  stop_signal: SIGINT
  <<: [ *penpot-depend ]

 penpot-redis:
  image: redis:7-alpine
  container_name: "penpot-redis"
  volumes:
   - "/app_base/penpot/redis:/data"
  sysctls:
   - net.core.somaxconn=4096
#  - vm.overcommit_memory=1
  command: redis-server --save 60 1 --loglevel warning
  <<: [ *penpot-depend ]

networks:
 penpot:
  driver: bridge
  name: penpot
EOT' && \
docker-compose -f /app/compose/penpot/penpot.yml config
```

#### up

```
docker-compose -f /app/compose/penpot/penpot.yml up -d
```

#### nginx proxy config

```
upstream http_penpot {
  server 192.168.5.249:9001;
}

server {
  listen 443 ssl http2;
  charset utf-8;

  server_name penpot.domain.ru;

  access_log /var/log/nginx/penpot.access.log main;
  error_log /var/log/nginx/penpot.error.log warn;

  include /etc/nginx/certs/ssl.conf;

  ssl_certificate /etc/nginx/certs/ssl/live/domain.ru/fullchain.pem;
  ssl_trusted_certificate /etc/nginx/certs/ssl/live/domain.ru/chain.pem;
  ssl_certificate_key /etc/nginx/certs/ssl/live/domain.ru/privkey.pem;

  add_header X-Content-Type-Options nosniff;

  location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Scheme $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_redirect off;
    proxy_pass http://http_penpot/;
  }
}
```

#### create local user

```
docker exec -it penpot-backend python3 ./manage.py create-profile -e admin@domain.ru -n Admin -p 12345678
```

### Expected behavior

logon with gitlab and password without free registration

### Actual behavior

```
POST https://penpot.domain.ru/api/auth/oauth/gitlab 400 (Bad Request)
POST https://penpot.domain.ru/api/rpc/command/login-with-password 400 (Bad Request)
```

### Desktop (please complete the following information)

Ubuntu Server 22 + Docker 24.0.2
