### ISSUE TITLE
What in the correct way to implement HealthCheck for Penpot in Docker Compose

### ISSUE THREAD

**Issue by moutasem1989** [uxbox/uxbox#4465]
In docker-compose.yml I trying to add healthcheck to Penpot Frontend.
Is this the most efficient way to implement it?
```
    healthcheck:
      test: curl --fail http://localhost:80/health || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
```
is there a way to implement it as well for Penpot Backend and Penpot Exporter?
