### ISSUE TITLE
bug: Workspace-Palette overlaps layer area and actions

### ISSUE THREAD

**Issue by pr0pz** [uxbox/uxbox#4508]
### Steps To Reproduce

1. Start self hosted version with docker compose
2. Open any project or create a new one

### Expected behavior

The Workspace-Palette shouldn't overlap the space reserved for the layers.
![image](https://github.com/penpot/penpot/assets/48486059/4af9f67b-f3a6-460a-926a-1f85b3cf1476)

### Actual behavior

The Workspace-Palette is overlapping the layers making it impossible to click on some layer action buttons if they get behind it.

![image](https://github.com/penpot/penpot/assets/48486059/8b1cb9cd-a07f-4209-8769-c73462ca29da)

### Screenshots or video

https://github.com/penpot/penpot/assets/48486059/455c5fd5-e76f-4e78-ad3d-61eb8d6cfd4f

### Desktop (please complete the following information)

- OS: macos sonoma 14.4.1
- Browser: Arc 1.39.1

### Environment (please complete the following information)

Self-Hosted:
- OS: macos sonoma 14.4.1
- Docker Desktop: 4.28.0 (139021)
- Compose: v2.24.6-desktop.1

<details>
<summary>docker-compose.yaml</summary>

```
---
version: "3.5"

networks:
  penpot:

volumes:
  penpot_postgres_v15:
  penpot_assets:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    ports:
      - 9001:80

    volumes:
      - penpot_assets:/opt/data/assets

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

    labels:
      - "traefik.enable=true"

    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always

    volumes:
      - penpot_assets:/opt/data/assets

    depends_on:
      - penpot-postgres
      - penpot-redis

    networks:
      - penpot
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification enable-smtp enable-prepl-server
      - PENPOT_PUBLIC_URI=http://localhost:9001
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=true
      - PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      - PENPOT_SMTP_HOST=penpot-mailcatch
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_USERNAME=
      - PENPOT_SMTP_PASSWORD=
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - penpot

    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT

    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data

    networks:
      - penpot

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot

  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - penpot
```
</details>

### Additional context

- When I resize the the left edge of the canvas, the Worspace-Palette snaps into the correct position
- But after scrolling inside the canvas, it change the position again overlapping the layer area (see video)
