### ISSUE TITLE
bug: Component font color not changing on duplicates

### ISSUE THREAD

**Issue by pr0pz** [uxbox/uxbox#4512]
### Steps To Reproduce

1. Start self hosted version with docker compose
2. Open any project or create a new one
3. Create a text element
4. Add a flex layout to it
5. Create a component of this element
6. Copy and paste this component elsewhere (so it's a child component)
7. Change the text of the copied element (text override)
8. Change the text color of the original component element

### Expected behavior

When I change the text color inside the main component I'd expect that all "child" components also change the text color, regardless if I changed the actual text. Actual Text and color are different overrides.

### Actual behavior

After changing the text of a child component, the text color wont sync with the main component. This would only make sense if I also changed the text color of the child component, not the text itself.

### Screenshots or video

https://github.com/penpot/penpot/assets/48486059/61ebcd32-1fef-4824-bdaf-692a23fe56d2

### Desktop (please complete the following information)

- OS: macos sonoma 14.4.1
- Browser: Arc 1.39.1

### Environment (please complete the following information)

Self-Hosted:
- OS: macos sonoma 14.4.1
- Docker Desktop: 4.28.0 (139021)
- Compose: v2.24.6-desktop.1

<details>
<summary>docker-compose.yaml</summary>

```
---
version: "3.5"

networks:
  penpot:

volumes:
  penpot_postgres_v15:
  penpot_assets:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    ports:
      - 9001:80

    volumes:
      - penpot_assets:/opt/data/assets

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

    labels:
      - "traefik.enable=true"

    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always

    volumes:
      - penpot_assets:/opt/data/assets

    depends_on:
      - penpot-postgres
      - penpot-redis

    networks:
      - penpot
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification enable-smtp enable-prepl-server
      - PENPOT_PUBLIC_URI=http://localhost:9001
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=true
      - PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      - PENPOT_SMTP_HOST=penpot-mailcatch
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_USERNAME=
      - PENPOT_SMTP_PASSWORD=
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - penpot

    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT

    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data

    networks:
      - penpot

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot

  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - penpot
```
</details>
