### ISSUE TITLE
Issue with Persistence of Errors After Upgrading to Penpot 2.0.1

### ISSUE THREAD

**Issue by kaicox** [uxbox/uxbox#4550]
Hello Team,

I recently upgraded Penpot from version 1.19.3 to 2.0.1 but continue to face the same issue. After deleting v2-migrated from server_prop and attempting to restart the containers, the issue persists. Observing the backend logs post-restart, I noticed the following entries:
```
[2024-05-06 08:03:26.043] I app.migrations.v2 - hint="v2 migration started"
[2024-05-06 08:03:26.088] I app.migrations.v2 - hint="v2 migration finished", files=nil, teams=nil, errors=nil, elapsed="0.083884949s"
```
Despite these indications of a successful migration, I am unable to open my project. The project does not load at all, as illustrated in the screenshot linked below:
![image](https://github.com/penpot/penpot/assets/52698333/04bc66a4-21da-4b61-b59b-17b7ba48774b)
Here is the Docker Compose configuration I am using:
```
version: "3.8"

networks:
  penpot:

volumes:
  penpot_postgres_data2:
  penpot_assets_data2:

services:
  penpot-frontend:
    image: "penpotapp/frontend:2.0.1"
    ports:
      - 80:80

    volumes:
      - ./penpot_assets_data2:/opt/data

    env_file:
      - config.env

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:2.0.1"
    volumes:
      - ./penpot_assets_data2:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    env_file:
      - config.env

    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:2.0.1"
    env_file:
      - config.env
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT
    ports:
      - 5432:5432
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

    volumes:
      - ./penpot_postgres_data2:/var/lib/postgresql/data

    networks:
      - penpot

  penpot-redis:
    image: "redis:7"
    restart: always
    networks:
      - penpot
  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - penpot
```
