### ISSUE TITLE
bug: selfhosted, reverse proxy, assets path gives 404 

### ISSUE THREAD

**Issue by a-super-admin** [uxbox/uxbox#4794]
### Steps To Reproduce

Docker Selfhosted. Registration and login works.
Import an example project or create a new project draft.
In the project overview the thumbnails are missing:
![image](https://github.com/penpot/penpot/assets/2656697/76034157-f90f-4142-b608-a2abb679b634)
The request throws a 404 not found.
console:
![image](https://github.com/penpot/penpot/assets/2656697/c2a09810-6da5-47b2-98de-7b0d19b079ae)

### Expected behavior

Thumbnails should show.

### Actual behavior

Thumbnails are not being loaded.

### Backend Stack Trace

```console
penpot-redis-1      | 1:M 23 Jun 2024 23:15:29.265 * Ready to accept connections tcp
penpot-backend-1    | [2024-06-24 15:00:00.041] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
penpot-mailcatch-1  | ==> http://0.0.0.0:1080
penpot-postgres-1   | 2024-06-24 15:30:51.706 UTC [27] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.814 s, sync=0.203 s, total=2.020 s; sync files=2, longest=0.200 s, average=0.102 s; distance=4 kB, estimate=44 kB
penpot-frontend-1   | 172.18.0.3 - - [24/Jun/2024:15:27:16 +0000] "GET /images/thumbnails/template-avataaars.jpg HTTP/1.1" 200 169555 "https://pen.mysite.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
penpot-exporter-1   | INF [app.redis] hint="redis connection established", uri="redis://penpot-redis/0"
```

### Additional context

> [!NOTE]
> compose:
```yml
volumes:
  penpot_assets:

networks:
  default:
    name: custom-network
    external: true

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: unless-stopped
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: unless-stopped
    volumes:
      - penpot_assets:/opt/data/assets      
    depends_on:
      - penpot-postgres
      - penpot-redis
    environment:
      - PENPOT_FLAGS=enable-login-with-password disable-email-verification enable-smtp enable-prepl-server
      - PENPOT_PUBLIC_URI=https://pen.mysite.com
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=false
      - PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      - PENPOT_SMTP_HOST=penpot-mailcatch
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_USERNAME=
      - PENPOT_SMTP_PASSWORD=
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: unless-stopped
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - ./docker-data/penpot-postgres/postgres_v15:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

  penpot-redis:
    image: redis:7
    restart: unless-stopped

  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: unless-stopped
    expose:
      - '1025'
    ports:
      - "1090:1080"
```

> [!NOTE]
> nginx reverse proxy:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name pen.mysite.com;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;
    include /config/nginx/authentik-server.conf;

    location / {
        include /config/nginx/authentik-location.conf;
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        # Allows websockets over HTTPS.
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        set $upstream_app penpot-frontend;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

**Comment by girafic** [comment]
Issue could be merged with https://github.com/penpot/penpot/issues/4704

**Comment by superalex** [comment]
Hello @wurst44 

Based on your docker-compose.yaml I created one for me including the nginx service:

```
volumes:
  penpot_assets:

networks:
  penpot:

services:
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf

  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: unless-stopped
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password disable-secure-session-cookies
    ports:
      - 9001:80

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: unless-stopped
    volumes:
      - penpot_assets:/opt/data/assets      
    depends_on:
      - penpot-postgres
      - penpot-redis
    environment:
      - PENPOT_FLAGS=enable-login-with-password disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies
      - PENPOT_PUBLIC_URI=http://pen.mysite.com
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=false
      - PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      - PENPOT_SMTP_HOST=penpot-mailcatch
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_USERNAME=
      - PENPOT_SMTP_PASSWORD=
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: unless-stopped
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - ./docker-data/penpot-postgres/postgres_v15:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

  penpot-redis:
    image: redis:7
    restart: unless-stopped

  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: unless-stopped
    expose:
      - '1025'
    ports:
      - "1090:1080"
```

The nginx-default.conf looks this way:

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    server_name pen.mysite.com;
    client_max_body_size 0;
    resolver 127.0.0.11 ipv6=off;

    location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        set $upstream_app penpot-frontend;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

Also in my /etc/hosts I added something like:
```
127.0.0.1 pen.mysite.com
```

And that way I can see the thumbnails correctly rendered:

![1](https://github.com/user-attachments/assets/1a17e500-bfa8-4da1-88dc-cebe8860b089)

Could you please update to the last penpot docker images and check if this is still happening?
