### ISSUE TITLE
feature: Creating SVG that appears black in light mode and light in dark mode

### ISSUE THREAD

**Issue by fugohan** [uxbox/uxbox#4897]
### Is your feature request related to a problem? Please describe.

Currently, when creating SVGs in Penpot, it's not possible to achieve a consistent visual representation across different themes (light/dark mode). This limitation leads to inconsistent branding and design across different platforms and interfaces. Specifically, SVGs appear either black in light mode or light in dark mode, but not both.

### Describe the solution you'd like.

I would like to have the ability to create SVGs that adapt to the current theme, so that they appear black in light mode and light in dark mode. This would allow designers to create consistent and context-aware visual assets that seamlessly integrate with various themes.

### Describe alternatives you've considered.

One alternative approach could be to create separate SVGs for light and dark modes, but this would lead to increased complexity, maintenance, and storage requirements. Another alternative could be to use CSS to override the SVG's fill color based on the current theme, but this might not be feasible or compatible with all use cases.

### Additional context

I've successfully achieved this functionality in Figma using CSS styles to adapt the SVG's fill color based on the system's preferred color scheme. Here's an example of the CSS code I used:
```css
<style>
  :root {
    --text-color: white;
    --accent-color-1: #BA122B;
    --accent-color-2: #069;

  }
  @media (prefers-color-scheme: dark) {
    :root {
      --text-color: #ffffff;
      --accent-color-1: #ff4d6a;
      --accent-color-2: #4db8ff;
    }
  }
  </style>
  ```
Unfortunately, I was unable to replicate this functionality in Penpot, and it would be fantastic if this could be achieved in Penpot as well. This feature would greatly enhance the overall design and branding experience in Penpot, especially for designers working on projects that require consistent visual identity across different platforms and themes. It would also enable designers to create more flexible and adaptive designs that can easily adapt to changing theme requirements.
