### ISSUE TITLE
bug: email verification FLAG seem not work

### ISSUE THREAD

**Issue by xubeiyan** [uxbox/uxbox#4901]
### Steps To Reproduce

I set the `docker-compose.yaml`, this parts
```yaml
penpot-backend:
    environment:
         - PENPOT_FLAGS=enable-registration enable-login-with-password disable-secure-session-cookies disable-email-verification disable-smtp
```

and restart docker by this command
```shell
docker compose -f docker-compose.yaml up
```
but it STILL shows the email verification part after register, also show the email content in the penpot-backend log

### Expected behavior

I run penpot in local network and need not email verification, but I tried every methods I could search, it still need an email verification

### Actual behavior

it still need an email verification

### Environment (please complete the following information)

- Host: local instance
- OS Version: Ubuntu 22.04
- Docker/Docker Compose Version：Docker version 27.0.3, build 7d4bcd8/Docker Compose version v2.28.1
- Image version: penpotapp/frontend:latest, penpotapp/backend:latest, sj26/mailcatcher:latest

### Backend Stack Trace

Seems it not reflect the email verification
```
penpot-backend-1    | [2024-07-22 09:07:58.406] I app.main - hint="welcome to penpot", flags="backend-openapi-doc,login-with-password,backend-api-doc,v2-migration,backend-worker,registration,insecure-register", worker?=true, version="2.1.0-13944-ge916c9749"
```
