### ISSUE TITLE
bug: Error exporting Penpot Self Hosted with Umbrel

### ISSUE THREAD

**Issue by lezzlo22** [uxbox/uxbox#5103]
### Steps To Reproduce

Open any file on Penpot
Try to export in any format

### Expected behavior

The file should be exported successfully in the selected format without causing a crash.

### Actual behavior

Application crashes when calling the export endpoint, Error 500

### Screenshots or video

![image](https://github.com/user-attachments/assets/ee486529-7c1a-49ca-9090-3928aea19f58)

### Desktop (please complete the following information)

Ubuntu, Umbrel as server.

### Environment (please complete the following information)

Ubuntu, Umbrel as server.

docker-compose.yml:

```
version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: penpot_penpot-frontend_1
      APP_PORT: 80
      # Can consider disabling auth all together. Penpot has its own auth system.
      PROXY_AUTH_WHITELIST: "/api/*"

  penpot-frontend:
    image: penpotapp/frontend:2.1.2@sha256:fabd50fb29567fb53ebf2aedd3f717b89f4b44b06a44414f2a29558b3f10ce55
    volumes:
      - ${APP_DATA_DIR}/data/assets:/opt/data/assets
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password
    depends_on:
      - penpot-backend
      - penpot-exporter
    restart: on-failure

  penpot-backend:
    image: penpotapp/backend:2.1.2@sha256:8c244f241d261620f50c02c0bd61e59b41c0e8dc96d3708c134076d6fb9187af
    # user 1000:1000 to avoid permission issues when importing libraries and templates
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/assets:/opt/data/assets
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification disable-smtp enable-prepl-server disable-secure-session-cookies
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=false
      # PENPOT_PUBLIC_URI needs to be set to in order to render thumbnails in the frontend
      - PENPOT_PUBLIC_URI=http://${DEVICE_DOMAIN_NAME}:${APP_PENPOT_UI_PORT}
    depends_on:
      - penpot-postgres
      - penpot-redis
    restart: on-failure

  penpot-exporter:
    image: penpotapp/exporter:2.1.2@sha256:e155660771dc2f966962efdb2b3c2aeedb4bfb50e8de18cacc0f4b2d12c6a90e
    user: "1000:1000"
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0
    restart: on-failure

  penpot-postgres:
    image: postgres:15@sha256:546445ad21cb5893c0997080b831ee45945e798c4359270e16413c8bd93575db
    user: "1000:1000"
    stop_signal: SIGINT
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot
    restart: on-failure
    
  penpot-redis:
    image: redis:7@sha256:45bfd95117a171ff9c1b5304bdae80a7a61eb5bbf0793d6a86c9078526ad88fa
    user: "1000:1000"
    restart: on-failure
```

### Backend Stack Trace

```console
Hint:    ResourceRequest timed out
Prof ID: 39b3be5d-7f03-81c1-8005-006a202c09c5
Team ID: 39b3be5d-7f03-81c1-8005-006a20367aac

Data:
{:type :server-error, :code :internal, :hint "ResourceRequest timed out", :data "(...)"}

{:type :internal, :code :timeout, :hint "ResourceRequest timed out"}

Trace:
Error: http error
  at new PENPOT.Dh (http://l.local:9001/js/shared.a1c78683f-1723021355.js:3476:33)
  at PENPOT.Eh (http://l.local:9001/js/shared.a1c78683f-1723021355.js:3476:355)
  at PENPOT.Fh (http://l.local:9001/js/shared.a1c78683f-1723021355.js:3476:308)
  at PENPOT.Tx (http://l.local:9001/js/shared.a1c78683f-1723021355.js:4423:110)
  at http://l.local:9001/js/shared.a1c78683f-1723021355.js:4397:236
  at u (http://l.local:9001/js/shared.a1c78683f-1723021355.js:242:276)
  at Q.p [as _nextOverride] (http://l.local:9001/js/shared.a1c78683f-1723021355.js:242:218)
  at Q.d [as _next] (http://l.local:9001/js/shared.a1c78683f-1723021355.js:149:99)
  at Q.next (http://l.local:9001/js/shared.a1c78683f-1723021355.js:158:12)
  at Q.next [as _nextOverride] (http://l.local:9001/js/shared.a1c78683f-1723021355.js:220:222)
  at Q.d [as _next] (http://l.local:9001/js/shared.a1c78683f-1723021355.js:149:99)
  at Q.next (http://l.local:9001/js/shared.a1c78683f-1723021355.js:158:12)
  at Q.next [as _nextOverride] (http://l.local:9001/js/shared.a1c78683f-1723021355.js:242:350)
  at Q.d [as _next] (http://l.local:9001/js/shared.a1c78683f-1723021355.js:149:99)
  at Q.next (http://l.local:9001/js/shared.a1c78683f-1723021355.js:158:12)
  at Q.next [as _nextOverride] (http://l.local:9001/js/shared.a1c78683f-1723021355.js:220:222)
  at Q.d [as _next] (http://l.local:9001/js/shared.a1c78683f-1723021355.js:149:99)
  at Q.next (http://l.local:9001/js/shared.a1c78683f-1723021355.js:158:12)
  at http://l.local:9001/js/shared.a1c78683f-1723021355.js:150:383

Last events:
[":app.main.data.dashboard/clear-file-select"
 ":app.main.data.dashboard/toggle-file-select"
 ":app.util.router/navigate"
 ":app.main.data.dashboard/go-to-workspace"
 ":app.util.router/navigated"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.dashboard/finalize"
 ":app.main.data.persistence/initialize-persistence"
 ":app.main.data.workspace.layout/ensure-layout"
 ":app.main.data.workspace/initialize-layout"
 ":app.main.data.messages/hide"
 ":app.main.features/initialize"
 ":app.main.data.comments/retrieve-comment-threads"
 ":app.main.data.workspace/fetch-bundle-stage-1"
 ":app.main.data.workspace/fetch-bundle"
 ":app.main.data.workspace/initialize-file"
 ":app.main.features/initialize"
 ":app.main.data.users/set-current-team"
 ":app.main.data.workspace/bundle-stage-1"
 ":app.main.data.workspace/fetch-bundle-stage-2"
 ":app.main.data.workspace/bundle-stage-2"
 ":app.main.data.workspace.notifications/handle-presence"
 ":app.main.data.workspace.notifications/initialize"
 ":app.main.data.workspace.shape-layout/initialize"
 ":app.main.data.fonts/load-team-fonts"
 ":app.main.data.workspace/bundle-fetched"
 ":app.main.data.workspace/workspace-data-loaded"
 ":app.main.data.workspace/libraries-fetched"
 ":app.main.data.fonts/team-fonts-loaded"
 ":app.main.data.workspace.fix-bool-contents/fix-bool-contents"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.fix-deleted-fonts/fix-deleted-fonts"
 ":app.main.data.workspace.fix-broken-shapes/fix-broken-shapes"
 ":app.main.data.workspace/workspace-initialized"
 ":app.util.router/navigate"
 ":app.main.data.workspace/go-to-page"
 ":app.util.router/navigated"
 ":app.main.data.workspace/preload-data-uris"
 ":app.main.data.workspace.thumbnails/watch-state-changes"
 ":app.main.data.workspace.libraries/watch-component-changes"
 ":app.main.data.workspace/initialize-page"
 ":app.main.data.workspace.viewport/initialize-viewport"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.exports/request-simple-export"
 ":app.main.data.exports/clear-export-state"
 ":app.main.data.events/event"]
```
