### ISSUE TITLE
bug: self-hosted, docker - OIDC provider not configured

### ISSUE THREAD

**Issue by 2silver** [uxbox/uxbox#5122]
### Steps To Reproduce

1. Setup penpot via Docker-Compose (only relevant parts)
```
services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.penpotfrontend-stripprefix.stripprefix.prefixes=/"
      - "traefik.http.routers.penpotfrontend.entrypoints=https"
      - "traefik.http.routers.penpotfrontend.middlewares=penpotfrontend-stripprefix,securityHeaders@file,compressContent@file"
      - "traefik.http.routers.penpotfrontend.rule=Host(`host.example.com`)"
      - "traefik.http.routers.penpotfrontend.tls=true"
    environment:
      - PENPOT_FLAGS=disable-registration enable-login-with-password enable-login-with-oidc webhooks enable-demo-warning
      - PENPOT_OIDC_CLIENT_ID=abc-def-ghijk-lmnop-qrstuvwx

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-postgres
      - penpot-redis
    networks:
      - penpot
    environment:
      - PENPOT_FLAGS=disable-registration enable-login-with-password enable-login-with-oidc disable-email-verification enable-smtp enable-prepl-server webhooks log-invitation-tokens
      - PENPOT_SECRET_KEY=secretkey
      - PENPOT_PUBLIC_URI=https://host.example.com
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      - PENPOT_SMTP_HOST=penpot-mailcatch
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_USERNAME=
      - PENPOT_SMTP_PASSWORD=
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false
      - PENPOT_OIDC_CLIENT_ID=abc-def-ghijk-lmnop-qrstuvwx
      - PENPOT_OIDC_BASE_URI=https://login.microsoftonline.com/someuniqueid/v2.0/.well-known/openid-configuration
      - PENPOT_OIDC_CLIENT_SECRET=abc-def-ghijk-lmnop-qrstuvwx
      - PENPOT_OIDC_SCOPES=openid,profile,email
```
2. Start Container
3. Try login via OpenID

Callback URL OpenID. 
`https://host.example.com/api/auth/oauth/generic/callback`

### Expected behavior

Login via OpenID / Microsoft Azure

### Actual behavior

1. Response via API
`["^ ","~:type","~:restriction","~:code","~:provider-not-configured","~:provider","~:generic","~:hint","provider not configured"]`
2. Error Log
`W app.auth.oidc - hint="unable to discover OIDC configuration"`

### Backend Trace

```
+ exec /opt/jdk/bin/java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlog4j2.configurationFile=log4j2.xml -XX:-OmitStackTraceInFastThrow -Dpolyglot.engine.WarnInterpreterOnly=false --enable-preview -jar penpot.jar -m app.main
[2024-09-25 13:01:08.714] W app.auth.oidc - hint="unable to discover OIDC configuration"
SUMMARY:
 →  java.net.ConnectException: null (HttpClientImpl.java:951)
 →  java.net.ConnectException: null (Utils.java:1028)
 →  java.nio.channels.UnresolvedAddressException: null (Net.java:137)
DETAIL:
 →  java.net.ConnectException: null (HttpClientImpl.java:951)
    at: jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:951)
        jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
        java_http_clj.core$send.invokeStatic(core.clj:154)
        java_http_clj.core$send.invoke(core.clj:148)
        app.http.client$send_BANG_.invokeStatic(client.clj:35)
        app.http.client$send_BANG_.invoke(client.clj:30)
        app.http.client$req_BANG_.invokeStatic(client.clj:61)
        app.http.client$req_BANG_.invoke(client.clj:53)
        app.auth.oidc$discover_oidc_config.invokeStatic(oidc.clj:59)
        app.auth.oidc$discover_oidc_config.invoke(oidc.clj:56)
        app.auth.oidc$prepare_oidc_opts.invokeStatic(oidc.clj:107)
        app.auth.oidc$prepare_oidc_opts.invoke(oidc.clj:83)
        app.auth.oidc$eval48807$fn__48808.invoke(oidc.clj:149)
        clojure.lang.MultiFn.invoke(MultiFn.java:234)
        integrant.core$try_build_action.invokeStatic(core.cljc:305)
        integrant.core$try_build_action.invoke(core.cljc:304)
        integrant.core$build_key.invokeStatic(core.cljc:313)
        integrant.core$build_key.invoke(core.cljc:309)
        clojure.core$partial$fn__5929.invoke(core.clj:2656)
        clojure.core.protocols$fn__8271.invokeStatic(protocols.clj:167)
        clojure.core.protocols/fn(protocols.clj:123)
        clojure.core.protocols$fn__8225$G__8220__8234.invoke(protocols.clj:19)
        clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        clojure.core.protocols$fn__8258.invokeStatic(protocols.clj:74)
        clojure.core.protocols/fn(protocols.clj:74)
        clojure.core.protocols$fn__8199$G__8194__8212.invoke(protocols.clj:13)
        clojure.core$reduce.invokeStatic(core.clj:6957)
        clojure.core$reduce.invoke(core.clj:6939)
        integrant.core$build.invokeStatic(core.cljc:337)
        integrant.core$build.invoke(core.cljc:316)
        integrant.core$init.invokeStatic(core.cljc:445)
        integrant.core$init.invoke(core.cljc:437)
        integrant.core$init.invokeStatic(core.cljc:442)
        integrant.core$init.invoke(core.cljc:437)
        app.main$start$fn__46989.invoke(main.clj:536)
        clojure.lang.AFn.applyToHelper(AFn.java:154)
        clojure.lang.AFn.applyTo(AFn.java:144)
        clojure.lang.Var.alterRoot(Var.java:310)
        clojure.core$alter_var_root.invokeStatic(core.clj:5555)
        clojure.core$alter_var_root.doInvoke(core.clj:5550)
        clojure.lang.RestFn.invoke(RestFn.java:428)
        app.main$start.invokeStatic(main.clj:530)
        app.main$start.invoke(main.clj:527)
        app.main$_main.invokeStatic(main.clj:596)
        app.main$_main.doInvoke(main.clj:588)
        clojure.lang.RestFn.invoke(RestFn.java:400)
        clojure.lang.AFn.applyToHelper(AFn.java:152)
        clojure.lang.RestFn.applyTo(RestFn.java:135)
        clojure.lang.Var.applyTo(Var.java:707)
        clojure.core$apply.invokeStatic(core.clj:667)
        clojure.main$main_opt.invokeStatic(main.clj:515)
        clojure.main$main_opt.invoke(main.clj:511)
        clojure.main$main.invokeStatic(main.clj:665)
        clojure.main$main.doInvoke(main.clj:617)
        clojure.lang.RestFn.applyTo(RestFn.java:140)
        clojure.lang.Var.applyTo(Var.java:707)
        clojure.main.main(main.java:40)
 →  java.net.ConnectException: null (Utils.java:1028)
    at: jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1028)
        jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:227)
        jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56)
        jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:468)
        jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:134)
        jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:94)
        jdk.internal.net.http.Exchange.establishExchange(Exchange.java:386)
        jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:570)
        jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:423)
        jdk.internal.net.http.Exchange.responseAsync(Exchange.java:415)
        jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:413)
        jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:454)
        java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)
        java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2372)
        jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:444)
        jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:346)
        java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:177)
        java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2719)
        jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:299)
        jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:1047)
        jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:930)
        jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
        java_http_clj.core$send.invokeStatic(core.clj:154)
        java_http_clj.core$send.invoke(core.clj:148)
        app.http.client$send_BANG_.invokeStatic(client.clj:35)
        app.http.client$send_BANG_.invoke(client.clj:30)
        app.http.client$req_BANG_.invokeStatic(client.clj:61)
        app.http.client$req_BANG_.invoke(client.clj:53)
        app.auth.oidc$discover_oidc_config.invokeStatic(oidc.clj:59)
        app.auth.oidc$discover_oidc_config.invoke(oidc.clj:56)
        app.auth.oidc$prepare_oidc_opts.invokeStatic(oidc.clj:107)
        app.auth.oidc$prepare_oidc_opts.invoke(oidc.clj:83)
        app.auth.oidc$eval48807$fn__48808.invoke(oidc.clj:149)
        clojure.lang.MultiFn.invoke(MultiFn.java:234)
        integrant.core$try_build_action.invokeStatic(core.cljc:305)
        integrant.core$try_build_action.invoke(core.cljc:304)
        integrant.core$build_key.invokeStatic(core.cljc:313)
        integrant.core$build_key.invoke(core.cljc:309)
        clojure.core$partial$fn__5929.invoke(core.clj:2656)
        clojure.core.protocols$fn__8271.invokeStatic(protocols.clj:167)
        clojure.core.protocols/fn(protocols.clj:123)
        clojure.core.protocols$fn__8225$G__8220__8234.invoke(protocols.clj:19)
        clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        clojure.core.protocols$fn__8258.invokeStatic(protocols.clj:74)
        clojure.core.protocols/fn(protocols.clj:74)
        clojure.core.protocols$fn__8199$G__8194__8212.invoke(protocols.clj:13)
        clojure.core$reduce.invokeStatic(core.clj:6957)
        clojure.core$reduce.invoke(core.clj:6939)
        integrant.core$build.invokeStatic(core.cljc:337)
        integrant.core$build.invoke(core.cljc:316)
        integrant.core$init.invokeStatic(core.cljc:445)
        integrant.core$init.invoke(core.cljc:437)
        integrant.core$init.invokeStatic(core.cljc:442)
        integrant.core$init.invoke(core.cljc:437)
        app.main$start$fn__46989.invoke(main.clj:536)
        clojure.lang.AFn.applyToHelper(AFn.java:154)
        clojure.lang.AFn.applyTo(AFn.java:144)
        clojure.lang.Var.alterRoot(Var.java:310)
        clojure.core$alter_var_root.invokeStatic(core.clj:5555)
        clojure.core$alter_var_root.doInvoke(core.clj:5550)
        clojure.lang.RestFn.invoke(RestFn.java:428)
        app.main$start.invokeStatic(main.clj:530)
        app.main$start.invoke(main.clj:527)
        app.main$_main.invokeStatic(main.clj:596)
        app.main$_main.doInvoke(main.clj:588)
        clojure.lang.RestFn.invoke(RestFn.java:400)
        clojure.lang.AFn.applyToHelper(AFn.java:152)
        clojure.lang.RestFn.applyTo(RestFn.java:135)
        clojure.lang.Var.applyTo(Var.java:707)
        clojure.core$apply.invokeStatic(core.clj:667)
        clojure.main$main_opt.invokeStatic(main.clj:515)
        clojure.main$main_opt.invoke(main.clj:511)
        clojure.main$main.invokeStatic(main.clj:665)
        clojure.main$main.doInvoke(main.clj:617)
        clojure.lang.RestFn.applyTo(RestFn.java:140)
        clojure.lang.Var.applyTo(Var.java:707)
        clojure.main.main(main.java:40)
 →  java.nio.channels.UnresolvedAddressException: null (Net.java:137)
    at: sun.nio.ch.Net.checkAddress(Net.java:137)
        sun.nio.ch.Net.checkAddress(Net.java:145)
        sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:842)
        sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:865)
        jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:210)
        java.security.AccessController.doPrivileged(AccessController.java:571)
        jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:212)
        jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56)
        jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:468)
        jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:134)
        jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:94)
        jdk.internal.net.http.Exchange.establishExchange(Exchange.java:386)
        jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:570)
        jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:423)
        jdk.internal.net.http.Exchange.responseAsync(Exchange.java:415)
        jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:413)
        jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:454)
        java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)
        java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2372)
        jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:444)
        jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:346)
        java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:177)
        java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2719)
        jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:299)
        jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:1047)
        jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:930)
        jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
        java_http_clj.core$send.invokeStatic(core.clj:154)
        java_http_clj.core$send.invoke(core.clj:148)
        app.http.client$send_BANG_.invokeStatic(client.clj:35)
        app.http.client$send_BANG_.invoke(client.clj:30)
        app.http.client$req_BANG_.invokeStatic(client.clj:61)
        app.http.client$req_BANG_.invoke(client.clj:53)
        app.auth.oidc$discover_oidc_config.invokeStatic(oidc.clj:59)
        app.auth.oidc$discover_oidc_config.invoke(oidc.clj:56)
        app.auth.oidc$prepare_oidc_opts.invokeStatic(oidc.clj:107)
        app.auth.oidc$prepare_oidc_opts.invoke(oidc.clj:83)
        app.auth.oidc$eval48807$fn__48808.invoke(oidc.clj:149)
        clojure.lang.MultiFn.invoke(MultiFn.java:234)
        integrant.core$try_build_action.invokeStatic(core.cljc:305)
        integrant.core$try_build_action.invoke(core.cljc:304)
        integrant.core$build_key.invokeStatic(core.cljc:313)
        integrant.core$build_key.invoke(core.cljc:309)
        clojure.core$partial$fn__5929.invoke(core.clj:2656)
        clojure.core.protocols$fn__8271.invokeStatic(protocols.clj:167)
        clojure.core.protocols/fn(protocols.clj:123)
        clojure.core.protocols$fn__8225$G__8220__8234.invoke(protocols.clj:19)
        clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        clojure.core.protocols$fn__8258.invokeStatic(protocols.clj:74)
        clojure.core.protocols/fn(protocols.clj:74)
        clojure.core.protocols$fn__8199$G__8194__8212.invoke(protocols.clj:13)
        clojure.core$reduce.invokeStatic(core.clj:6957)
        clojure.core$reduce.invoke(core.clj:6939)
        integrant.core$build.invokeStatic(core.cljc:337)
        integrant.core$build.invoke(core.cljc:316)
        integrant.core$init.invokeStatic(core.cljc:445)
        integrant.core$init.invoke(core.cljc:437)
        integrant.core$init.invokeStatic(core.cljc:442)
        integrant.core$init.invoke(core.cljc:437)
        app.main$start$fn__46989.invoke(main.clj:536)
        clojure.lang.AFn.applyToHelper(AFn.java:154)
        clojure.lang.AFn.applyTo(AFn.java:144)
        clojure.lang.Var.alterRoot(Var.java:310)
        clojure.core$alter_var_root.invokeStatic(core.clj:5555)
        clojure.core$alter_var_root.doInvoke(core.clj:5550)
        clojure.lang.RestFn.invoke(RestFn.java:428)
        app.main$start.invokeStatic(main.clj:530)
        app.main$start.invoke(main.clj:527)
        app.main$_main.invokeStatic(main.clj:596)
        app.main$_main.doInvoke(main.clj:588)
        clojure.lang.RestFn.invoke(RestFn.java:400)
        clojure.lang.AFn.applyToHelper(AFn.java:152)
        clojure.lang.RestFn.applyTo(RestFn.java:135)
        clojure.lang.Var.applyTo(Var.java:707)
        clojure.core$apply.invokeStatic(core.clj:667)
        clojure.main$main_opt.invokeStatic(main.clj:515)
        clojure.main$main_opt.invoke(main.clj:511)
        clojure.main$main.invokeStatic(main.clj:665)
        clojure.main$main.doInvoke(main.clj:617)
        clojure.lang.RestFn.applyTo(RestFn.java:140)
        clojure.lang.Var.applyTo(Var.java:707)
        clojure.main.main(main.java:40)
[2024-09-25 13:01:08.719] W app.auth.oidc - hint="unable to initialize auth provider, missing configuration", provider="oidc"
[2024-09-25 13:01:08.719] I app.metrics - action="initialize metrics"
[2024-09-25 13:01:08.724] I app.db - hint="initialize connection pool", name="main", uri="postgresql://penpot-postgres/penpot", read-only=false, with-credentials=true, min-size=0, max-size=60
[2024-09-25 13:01:08.750] I app.migrations - hint="running migrations", module=:app.migrations/migrations
[2024-09-25 13:01:09.181] I app.worker.executor - hint="executor started"
[2024-09-25 13:01:09.183] I app.redis - hint="initialize redis resources", uri="redis://penpot-redis/0", io-threads=3, worker-threads=3, connect?=nil
[2024-09-25 13:01:09.375] I app.msgbus - hint="initialize msgbus", buffer-size=128
[2024-09-25 13:01:09.831] I app.svgo - hint="initializing svg optimizer pool"
[2024-09-25 13:01:11.654] I app.http - hint="starting http server", port=6060, host="0.0.0.0"
[2024-09-25 13:01:11.673] I io.undertow - starting server: Undertow - 2.3.10.Final
[2024-09-25 13:01:11.679] I org.xnio - XNIO version 3.8.8.Final
[2024-09-25 13:01:11.684] I org.xnio.nio - XNIO NIO Implementation Version 3.8.8.Final
[2024-09-25 13:01:11.705] I org.jboss.threads - JBoss Threads version 3.5.0.Final
[2024-09-25 13:01:11.773] I app.loggers.database - hint="initializing database error persistence"
[2024-09-25 13:01:11.780] I app.storage.tmp - hint="started tmp cleaner", default-min-age="1h"
[2024-09-25 13:01:11.790] I app.worker - hint="registry initialized", tasks=14
[2024-09-25 13:01:11.795] I app.worker.cron - hint="started", tasks=8
[2024-09-25 13:01:11.811] I app.worker.dispatcher - hint="started"
[2024-09-25 13:01:11.814] I app.worker.executor - hint="monitor started", name="default"
[2024-09-25 13:01:11.821] I app.worker.runner - hint="started", id=0, queue="default"
[2024-09-25 13:01:11.827] I app.worker.runner - hint="started", id=0, queue="webhooks"
[2024-09-25 13:01:11.829] I app.srepl - hint="initializing repl server", name="prepl", port=6063, host="localhost"
[2024-09-25 13:01:11.839] I app.main - hint="welcome to penpot", flags="backend-openapi-doc,login-with-password,backend-api-doc,secure-session-cookies,v2-migration,backend-worker,login-with-oidc,smtp,prepl-server", worker?=true, version="2.1.4-14035-g689aab32c"
```
