### ISSUE TITLE
bug: Live editing and assets not working

### ISSUE THREAD

**Issue by mcquenji** [uxbox/uxbox#5140]
### Steps To Reproduce

`docker compose up -d` using the following compose file:

```yaml
networks:
  penpot:

volumes:
  penpot_postgres_v15:
  penpot_assets:
  minio:


services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    ports:
      - 9800:80

    volumes:
      - penpot_assets:/opt/data/assets

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

    ## Configuration envronment variables for frontend the container. In this case this
    ## container only needs the `PENPOT_FLAGS`. This environment variable is shared with
    ## other services but not all flags are relevant to all services.

    environment:
      ## Relevant flags for frontend:
      ## - demo-users
      ## - login-with-github
      ## - login-with-gitlab
      ## - login-with-google
      ## - login-with-ldap
      ## - login-with-oidc
      ## - login-with-password
      ## - registration
      ## - webhooks
      ##
      ## You can read more about all available flags on:
      ## https://help.penpot.app/technical-guide/configuration/#advanced-configuration

      - PENPOT_FLAGS=${PENPOT_FLAGS}

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always

    ports:
      - 9860:6060

    volumes:
      - penpot_assets:/opt/data/assets

    depends_on:
      - penpot-postgres
      - penpot-redis
      - minio

    networks:
      - penpot

    ## Configuration envronment variables for backend the
    ## container.

    environment:

      ## Relevant flags for backend:
      ## - demo-users
      ## - email-verification
      ## - log-emails
      ## - log-invitation-tokens
      ## - login-with-github
      ## - login-with-gitlab
      ## - login-with-google
      ## - login-with-ldap
      ## - login-with-oidc
      ## - login-with-password
      ## - registration
      ## - secure-session-cookies
      ## - smtp
      ## - smtp-debug
      ## - telemetry
      ## - webhooks
      ## - prepl-server
      ##
      ## You can read more about all available flags and other
      ## environment variables for the backend here:
      ## https://help.penpot.app/technical-guide/configuration/#advanced-configuration

      - PENPOT_FLAGS=${PENPOT_FLAGS}

      ## Penpot SECRET KEY. It serves as a master key from which other keys for subsystems
      ## (eg http sessions, or invitations) are derived.
      ##
      ## If you going to uncomment this, we recommend use here a trully randomly generated
      ## 512 bits base64 encoded string.  You can generate one with:
      ##
      ## python3 -c "import secrets; print(secrets.token_urlsafe(64))"

      - PENPOT_SECRET_KEY=${PENPOT_SECRET_KEY}

      ## The PREPL host. Mainly used for external programatic access to penpot backend
      ## (example: admin). By default it listen on `localhost` but if you are going to use
      ## the `admin`, you will need to uncomment this and set the host to `0.0.0.0`.

      # - PENPOT_PREPL_HOST=0.0.0.0

      ## Public URI. If you are going to expose this instance to the internet and use it
      ## under different domain than 'localhost', you will need to adjust it to the final
      ## domain.
      ##
      ## Consider using traefik and set the 'disable-secure-session-cookies' if you are
      ## not going to serve penpot under HTTPS.

      - PENPOT_PUBLIC_URI=${PENPOT_PUBLIC_URI}

      ## Database connection parameters. Don't touch them unless you are using custom
      ## postgresql connection parameters.

      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot

      ## Redis is used for the websockets notifications. Don't touch unless the redis
      ## container has different parameters or different name.

      - PENPOT_REDIS_URI=redis://penpot-redis/0

      ## Default configuration for assets storage: using filesystem based with all files
      ## stored in a docker volume.

      #- PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets

      ## Telemetry. When enabled, a periodical process will send anonymous data about this
      ## instance. Telemetry data will enable us to learn on how the application is used,
      ## based on real scenarios. If you want to help us, please leave it enabled. You can
      ## audit what data we send with the code available on github

      - PENPOT_TELEMETRY_ENABLED=true

      ## SMTP/Email configuration.
      - PENPOT_SMTP_DEFAULT_FROM=${SMTP_FROM}
      - PENPOT_SMTP_DEFAULT_REPLY_TO=${SMTP_REPLY_TO}
      - PENPOT_SMTP_HOST=${SMTP_HOST}
      - PENPOT_SMTP_PORT=${SMTP_PORT}
      - PENPOT_SMTP_USERNAME=${SMTP_USERNAME}
      - PENPOT_SMTP_PASSWORD=${SMTP_PASSWORD}
      - PENPOT_SMTP_TLS=true
      - PENPOT_SMTP_SSL=false

      # OIDC
      - PENPOT_OIDC_CLIENT_ID=${OIDC_CLIENT}

      # Mainly used for auto discovery the openid endpoints
      - PENPOT_OIDC_BASE_URI=${OIDC_ISSUER}
      - PENPOT_OIDC_CLIENT_SECRET=${OIDC_SECRET}
      - PENPOT_OIDC_SCOPES=openid profile email
      - PENPOT_OIDC_AUTH_URI=${OIDC_ISSUER}/oauth/v2/authorize
      - PENPOT_OIDC_TOKEN_URI=${OIDC_ISSUER}/oauth/v2/token
      - PENPOT_OIDC_USER_URI=${OIDC_ISSUER}/oidc/v1/userinfo

      # minio
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-s3
      - PENPOT_STORAGE_ASSETS_S3_ENDPOINT=http://minio:9000
      - PENPOT_STORAGE_ASSETS_S3_BUCKET=${AWS_S3_UPLOAD_BUCKET_NAME}

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - penpot

    ports:
      - 9861:6061

    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=${PENPOT_PUBLIC_URI}

      ## Redis is used for the websockets notifications.
      - PENPOT_REDIS_URI=redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT

    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data

    networks:
      - penpot

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot

  minio:
    image: minio/minio
    env_file: stack.env
    volumes:
      - minio:/data
    restart: always
    entrypoint: sh
    command: -c 'minio server --console-address ":9001" /data'
    networks:
      - penpot

  createbuckets:
    image: minio/mc
    env_file: stack.env
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb --ignore-existing --region --region=eu-central-1 minio/${AWS_S3_UPLOAD_BUCKET_NAME};
      /usr/bin/mc anonymous set public minio/${AWS_S3_UPLOAD_BUCKET_NAME};
      /usr/bin/mc admin user svcacct add --access-key "${AWS_ACCESS_KEY_ID}" --secret-key "${AWS_SECRET_ACCESS_KEY}" minio ${MINIO_ROOT_USER};
      exit 0;
      "
    networks:
      - penpot
 ```
 
 and the following nginx config:
 
 ```nginx
 server {
    listen 443 ssl;
    server_name penpot.*;
    client_max_body_size 0;
        location @handle_redirect {
            set $redirect_uri "$upstream_http_location";
            set $redirect_host "$upstream_http_x_host";
            set $redirect_cache_control "$upstream_http_cache_control";
            set $real_mtype "$upstream_http_x_mtype";

            proxy_buffering off;

            proxy_set_header Host "$redirect_host";
            proxy_hide_header etag;
            proxy_hide_header x-amz-id-2;
            proxy_hide_header x-amz-request-id;
            proxy_hide_header x-amz-meta-server-side-encryption;
            proxy_hide_header x-amz-server-side-encryption;
            proxy_pass $redirect_uri;

            add_header x-internal-redirect "$redirect_uri";
            add_header x-cache-control "$redirect_cache_control";
            add_header cache-control "$redirect_cache_control";
            add_header content-type "$real_mtype";
        }
      location /assets {
        proxy_pass http://docker-host:9860/assets;
        recursive_error_pages on;
        proxy_intercept_errors on;
        error_page 301 302 307 = @handle_redirect;
    }
    location /api/export {
            proxy_pass http://docker-host:9861;
        }

        location /api {
            proxy_pass http://docker-host:9860/api;
        }

    
    location /ws/notifications {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_pass http://docker-host:9860/ws/notifications;
    }
    location / {
        proxy_pass http://docker-host:9800;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

### Expected behavior

- Multiplayer edit working
- Assets loading

### Actual behavior

- Boards are not showing unless hovering over them
- Thumbnails aren't loading
- We have to refresh everytime to see each others changes

### Screenshots or video

![image](https://github.com/user-attachments/assets/8f4eeee9-ae52-4a52-9bfd-443cd09a8fa4)
![image](https://github.com/user-attachments/assets/6ba46e47-11ef-404f-a2d4-1da26e3e7433)
![image](https://github.com/user-attachments/assets/8d0ec941-c33f-45e5-b7d2-5b8935fd62d1)
![image](https://github.com/user-attachments/assets/c2f3ddd2-ef75-4f22-a786-428b699f4863)

### Desktop (please complete the following information)

- Chrome (Latest stable)
- Firefox (Latest stable)
- Edge (Latest stable)

### Environment (please complete the following information)

Selfhosted (Debian Bookworm)

### Frontend Stack Trace

```console
None
```

### Backend Stack Trace

```console
None
```

### Additional context

please note that nginx is running on a different VM than the docker host
