### ISSUE TITLE
bug: received incomplete profile info object (please set correct scopes) OIDC

### ISSUE THREAD

**Issue by iriderpro** [uxbox/uxbox#5426]
### Steps To Reproduce

Hi all! 
Penpot version 2.3.0
I use ms adfs provider.
config front
`      - PENPOT_FLAGS=enable-registration enable-login-with-password disable-secure-session-cookies enable-insecure-register enable-login-with-oidc enable-oidc-registration
`
config back
`     - PENPOT_OIDC_CLIENT_ID=491b33ed-877b-42aa-ba2c-831e1b008888
      - PENPOT_OIDC_BASE_URI=https://adfs2.company.com/adfs/
      - PENPOT_OIDC_CLIENT_SECRET=RpihaElNf7k1CY8i9XwK1-XnHbrTv12JsqhnU9sy
      - PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies enable-insecure-register enable-login-with-oidc enable-oidc-registration
`

### Expected behavior

I expect to be logged in

### Actual behavior

I am not logged in, but always redirected to the frontpage

### Desktop (please complete the following information)

Windows 10 Pro
Chrome 131.0.6778.108

### Frontend Stack Trace

```console
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:25 +0000] "GET / HTTP/1.1" 200 565758 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:25 +0000] "GET /js/config.js?ts=1730739141099 HTTP/1.1" 200 149 "http://10.0.59.111:9001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:25 +0000] "HEAD / HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:25 +0000] "GET /rasterizer.html HTTP/1.1" 200 320 "http://10.0.59.111:9001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:25 +0000] "GET /js/config.js?ts=1730739141099 HTTP/1.1" 200 149 "http://10.0.59.111:9001/rasterizer.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:25 +0000] "GET /api/rpc/command/get-profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:26 +0000] "GET /api/rpc/command/get-profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:30 +0000] "POST /api/auth/oauth/oidc HTTP/1.1" 200 447 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:31 +0000] "GET /api/auth/oauth/oidc/callback?code=2PzMMBQpckejGeqG5avmJw.ihMnHAwV3QgsCdbjFejQvCw39so.LAqh3SWhGMmvq4YIoD9E9-veXlOtUUO2cm1E99Th0kRQ88AbieImKW053HMRXiV-ZVWxBZuaA8tQ2NBHXXdWD5ebKm1tbTnGe-BXesspWr4R6hG_AOxMSLLStk7TjxGPR4eLEZ8UwuTPxypHUrK8OdMp-89RfH6xrit_3J21mVx3T7OOFwMieD64-pWLI-hM50yucDQT3yQDtIjHr5qgHigtxNL3SOPQQXnHvhlmJJPkAn2xcedUt6o9JB4v3R8eMPD1hwT3PrxA50nG1jv7VQAneGtiy90rAqhA2xOMeTy7kwnVy6Qyfjrlj5uLDR_8WJuDc6-2Pjr5uOt43DjHwQ&state=eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2R0NNIn0.t_MD1vPUTyeWx6y9ahQCVTuMmEMUFscwhqwyEBRGxTmABvPFDJmvag.-IakbF492WfkOPKl.phxD9aeWRNPE96uQzb5XEB1rhgDL4kGOzwj5CPTJXzix_JqouzulKM4Cc0nLwGqB1kfMKJ3fOhJT8wxhpewm3xNFml6HH4cbTJTGBabYS1QGYMPFOhhQa-K8lGrq.HhWH3Ms_y5uZvSjHXLyxhQ HTTP/1.1" 302 0 "http://10.0.59.111:9001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:31 +0000] "GET / HTTP/1.1" 200 565758 "http://10.0.59.111:9001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:31 +0000] "GET /js/config.js?ts=1730739141099 HTTP/1.1" 200 149 "http://10.0.59.111:9001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:31 +0000] "HEAD / HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:31 +0000] "GET /api/rpc/command/get-profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:31 +0000] "GET /rasterizer.html HTTP/1.1" 200 320 "http://10.0.59.111:9001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-frontend-1  | 10.9.1.219 - - [05/Dec/2024:09:06:31 +0000] "GET /js/config.js?ts=1730739141099 HTTP/1.1" 200 149 "http://10.0.59.111:9001/rasterizer.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
```

### Backend Stack Trace

```console
penpot-backend-1    | [2024-12-05 09:06:31.333] W app.auth.oidc - hint="received incomplete profile info object (please set correct scopes)", info={:backend "oidc", :fullname nil, :email nil, :props {:oidc/pwd_exp "3882166", :oidc/auth_time 1733387648, :oidc/nbf 1733389591, :oidc/upn "nik.pro@*******.int", :oidc/unique_name "****\\Nik.Pro"}}
penpot-backend-1    | [2024-12-05 09:06:31.342] E app.auth.oidc - hint="error on oauth process"
penpot-backend-1    | SUMMARY:
penpot-backend-1    |  →  clojure.lang.ExceptionInfo: inconmplete user info (oidc.clj:449)
penpot-backend-1    | DETAIL:
penpot-backend-1    |  →  clojure.lang.ExceptionInfo: inconmplete user info (oidc.clj:449)
penpot-backend-1    |     at: app.auth.oidc$get_info.invokeStatic(oidc.clj:449)
penpot-backend-1    |         app.auth.oidc$get_info.invoke(oidc.clj:431)
penpot-backend-1    |         app.auth.oidc$callback_handler.invokeStatic(oidc.clj:629)
penpot-backend-1    |         app.auth.oidc$callback_handler.invoke(oidc.clj:624)
penpot-backend-1    |         app.auth.oidc$fn__49248$fn__49250$fn__49252.invoke(oidc.clj:652)
penpot-backend-1    |         app.http.session$wrap_authz$fn__22765.invoke(session.clj:227)
penpot-backend-1    |         app.http.middleware$fn__55432$fn__55433$fn__55434.invoke(middleware.clj:245)
penpot-backend-1    |         app.http.session$wrap_soft_auth$fn__22759.invoke(session.clj:216)
penpot-backend-1    |         app.http.middleware$wrap_errors$fn__55423.invoke(middleware.clj:204)
penpot-backend-1    |         app.http.middleware$wrap_parse_request$fn__55342.invoke(middleware.clj:93)
penpot-backend-1    |         app.http.middleware$wrap_format_response$fn__55420.invoke(middleware.clj:193)
penpot-backend-1    |         yetti.middleware$wrap_params$fn__55318.invoke(middleware.clj:39)
penpot-backend-1    |         yetti.middleware$wrap_server_timing$fn__55327.invoke(middleware.clj:51)
penpot-backend-1    |         clojure.core$partial$fn__5925.invoke(core.clj:2640)
penpot-backend-1    |         app.http$router_handler$fn__56969.invoke(http.clj:126)
penpot-backend-1    |         yetti.adapter$dispatch_fn$fn__50574$fn__50575.invoke(adapter.clj:96)
penpot-backend-1    |         yetti.adapter$dispatch_fn$fn__50574.invoke(adapter.clj:95)
penpot-backend-1    |         yetti.adapter$create_handler$reify__50585$fn__50586.invoke(adapter.clj:122)
penpot-backend-1    |         clojure.lang.AFn.run(AFn.java:22)
penpot-backend-1    |         java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
penpot-backend-1    |         java.lang.VirtualThread.run(VirtualThread.java:309)
penpot-backend-1    |     dt: {:type :internal,
penpot-backend-1    |          :code :incomplete-user-info,
penpot-backend-1    |          :hint "inconmplete user info",
penpot-backend-1    |          :info
penpot-backend-1    |          {:backend "oidc",
penpot-backend-1    |           :fullname nil,
penpot-backend-1    |           :email nil,
penpot-backend-1    |           :props
penpot-backend-1    |           {:oidc/pwd_exp "3882166",
penpot-backend-1    |            :oidc/auth_time 1733387648,
penpot-backend-1    |            :oidc/nbf 1733389591,
penpot-backend-1    |            :oidc/upn "nik.pro@********.int",
penpot-backend-1    |            :oidc/unique_name "***\\Nik.Pro"}}}
penpot-backend-1    |
```

**Comment by iriderpro** [comment]
i added scope = allatclaims on ADFS and I was able to login.

**Comment by unsubscrieb** [comment]
I am getting this error using authelia as OIDC, I'm unable to check which scope is missing to get SSO working with Penpot
Authelia config
```
      - client_id: '-----'
        client_name: 'Penpot'
        client_secret: {{ secret "/secrets/oidc/clients/penpot/client_digest" | mindent 0 "|" | msquote }}
        public: false
        authorization_policy: 'one-factor'
        scopes:
          - openid
          - profile
          - email
          - groups
        redirect_uris:
          - 'https://-----/api/auth/oauth/oidc/callback'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
```

Penpot config
```
      PENPOT_OIDC_CLIENT_ID: -----
      PENPOT_OIDC_BASE_URI: https://-----
      PENPOT_OIDC_CLIENT_SECRET: -----
      PENPOT_OIDC_SCOPES: "email profile openid"
```

**Comment by ninioperdido** [comment]
I'm experiencing the same problem as @unsubscrieb, before penpot + authelia was working fine. Not on the latest versions.
Penpot config:
```
- id: penpot
        description: penpot
        secret:  mysecret
        public: false
        authorization_policy: one_factor
        scopes:
          - openid
          - email
          - profile
        redirect_uris:
          - https://mypenpoturl/api/auth/oauth/oidc/callback
        response_types:
          - code
        grant_types:
          - refresh_token
          - authorization_code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none
        token_endpoint_auth_method: "client_secret_post"

```
Penpot config:
```
      - PENPOT_OIDC_BASE_URI=https://myautheliaurl
      - PENPOT_OIDC_CLIENT_SECRET=mysecret
      - PENPOT_OIDC_NAME_ATTR=username
      - PENPOT_OIDC_SCOPES=openid email profile
      - PENPOT_OIDC_USER_URI=https://myautheliaurl/login/oauth/userinfo
      - PENPOT_OIDC_USERINFO_SOURCE=userinfo
      - PENPOT_FLAGS=enable-login-with-oidc enable-log-invitation-tokens enable-oidc-registration
```

**Comment by unsubscrieb** [comment]
I have it working now with Authelia

Penpot-backend env
```
PENPOT_OIDC_CLIENT_ID: [client id]
PENPOT_OIDC_BASE_URI: https://auth.[domain]
PENPOT_OIDC_CLIENT_SECRET: [client secret]
PENPOT_OIDC_SCOPES: "email profile openid"
```

Authelia configuration.yml
Added `identity_providers.oidc.claims_policies` and Penpot client `claims_policy`
```
identity_providers:
  oidc:
    claims_policies:
      all:
        id_token: ['groups', 'email', 'email_verified', 'alt_emails', 'preferred_username', 'name']

      - client_id: '[client id]'
        client_name: 'Penpot'
        client_secret: {{ secret "/secrets/oidc/clients/penpot/client_digest" | mindent 0 "|" | msquote }}
        public: false
        authorization_policy: 'one-factor'
        claims_policy: all
        scopes:
          - openid
          - profile
          - email
          - groups
        redirect_uris:
          - 'https://[penpot url]/api/auth/oauth/oidc/callback'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
```
