### ISSUE TITLE
bug: 502 error (Bad Gateway) on login screen (/api/rpc/command/get-profile) Penpot 4.2.1

### ISSUE THREAD

**Issue by BrianGilbert** [uxbox/uxbox#5564]
### Steps To Reproduce

Today I updated to penpot 2.4.1 images and after restarting penpot am unable use it anymore, I tried going back to older images and the problem persisted, I deleted the database and tried to set up as a new instance and still stuck on bad gateway error.

Penpot is running on one of two Synology servers on our network the other Synology server acting is proxy and managing SSL cert via lets encrypt.

<img width="585" alt="Storehouse - Synology DiskStation 2025-01-13 15-32-42" src="https://github.com/user-attachments/assets/04f353d2-80aa-4c27-93ca-9bdc273c04c4" />

<img width="579" alt="Storehouse - Synology DiskStation 2025-01-13 15-33-24" src="https://github.com/user-attachments/assets/9eacedd1-9b73-43c7-887f-0aa9e2a86aef" />

<img width="585" alt="Storehouse - Synology DiskStation 2025-01-13 15-33-52" src="https://github.com/user-attachments/assets/65421768-8158-4520-aa84-cf1ad57932c7" />

These settings are unchanged from the previously working state before I updated to 2.4.1

### Expected behavior

dashboard to load successfully

### Actual behavior

Penpot bad gateway error screen displayed

### Screenshots or video

<img width="996" alt=" 2025-01-13 14-42-16" src="https://github.com/user-attachments/assets/9fcb00e4-f016-4689-a4e5-747f7aa9e209" />

![Realityloop - Synology DiskStation 2025-01-13 15-27-24](https://github.com/user-attachments/assets/4bc36f61-81f1-4887-abea-90dc2074b1ba)

### Desktop (please complete the following information)

-MacOS
-Firefox Nightly (updated today)
-Edge

### Environment (please complete the following information)

OS Version: Linux 3.10.108 #72803 x86_64 GNU/Linux synology_braswell_916+
Docker version: 20.10.23, build 876964a

```
CONTAINER ID   IMAGE                                      COMMAND                  CREATED             STATUS             PORTS                                                           NAMES
4a8ae158de44   penpotapp/frontend:2.4.1                   "/bin/bash /entrypoi…"   14 minutes ago      Up 14 minutes      0.0.0.0:9010->8080/tcp, :::9010->8080/tcp                       penpot-penpot-frontend-1
ccf7afd125b5   penpotapp/backend:2.4.1                    "/bin/bash run.sh"       14 minutes ago      Up 50 seconds                                                                      penpot-penpot-backend-1
4f24d341a56b   penpotapp/exporter:2.4.1                   "node app.js"            About an hour ago   Up About an hour                                                                   penpot-penpot-exporter-1
0b4b639b66f6   postgres:15                                "docker-entrypoint.s…"   About an hour ago   Up About an hour   5432/tcp                                                        penpot-penpot-postgres-1
c1f5a4a1e8a7   redis:7.2                                  "docker-entrypoint.s…"   About an hour ago   Up About an hour   6379/tcp                                                        penpot-penpot-redis-1
```

Docker compose (edited for security):
```
---
version: "3.8"

networks:
  penpot:

#volumes:
  # penpot_postgres_v15:
  # penpot_assets:
  # penpot_traefik:
  # penpot_minio:

services:
  ## Traefik service declaration example. Consider using it if you are going to expose
  ## penpot to the internet or different host than `localhost`.

  # traefik:
  #   image: traefik:v2.9
  #   networks:
  #     - penpot
  #   command:
  #     - "--api.insecure=true"
  #     - "--entryPoints.web.address=:80"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entryPoints.websecure.address=:443"
  #     - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
  #     - "--certificatesresolvers.letsencrypt.acme.email=<EMAIL_ADDRESS>"
  #     - "--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json"
  #   volumes:
  #     - "penpot_traefik:/traefik"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   ports:
  #     - "80:80"
  #     - "443:443"

  penpot-frontend:
    image: "penpotapp/frontend:2.4.1"
    restart: always
    ports:
      - 9010:8080
    
    security_opt:
      - no-new-privileges:true
      
    volumes:
      - /volume1/docker/penpot/assets:/opt/data/assets:rw

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

    labels:
      - "traefik.enable=true"

      ## HTTP: example of labels for the case if you are going to expose penpot to the
      ## internet using only HTTP (without HTTPS) with traefik

      # - "traefik.http.routers.penpot-http.entrypoints=web"
      # - "traefik.http.routers.penpot-http.rule=Host(`<DOMAIN_NAME>`)"
      # - "traefik.http.services.penpot-http.loadbalancer.server.port=80"

      ## HTTPS: example of labels for the case if you are going to expose penpot to the
      ## internet using with HTTPS using traefik

      # - "traefik.http.middlewares.http-redirect.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.http-redirect.redirectscheme.permanent=true"
      # - "traefik.http.routers.penpot-http.entrypoints=web"
      # - "traefik.http.routers.penpot-http.rule=Host(`penpot.domain.com`)"
      # - "traefik.http.routers.penpot-http.middlewares=http-redirect"
      # - "traefik.http.routers.penpot-https.entrypoints=websecure"
      # - "traefik.http.routers.penpot-https.rule=Host(`penpot.domain.com`)"
      # - "traefik.http.services.penpot-https.loadbalancer.server.port=80"
      # - "traefik.http.routers.penpot-https.tls=true"
      # - "traefik.http.routers.penpot-https.tls.certresolver=letsencrypt"

    ## Configuration envronment variables for frontend the container. In this case this
    ## container only needs the `PENPOT_FLAGS`. This environment variable is shared with
    ## other services but not all flags are relevant to all services.

    environment:
      ## Relevant flags for frontend:
      ## - demo-users
      ## - login-with-github
      ## - login-with-gitlab
      ## - login-with-google
      ## - login-with-ldap
      ## - login-with-oidc
      ## - login-with-password
      ## - registration
      ## - webhooks
      ##
      ## You can read more about all available flags on:
      ## https://help.penpot.app/technical-guide/configuration/#advanced-configuration

      - PENPOT_FLAGS=disable-secure-session-cookies enable-registration enable-login-with-gitlab enable-insecure-register disable-login-with-password disable-email-verification enable-smtp enable-prepl-server

      - PENPOT_GITLAB_BASE_URI=https://git.domain.com

  penpot-backend:
    image: "penpotapp/backend:2.4.1"
    restart: always
    
    security_opt:
      - no-new-privileges:true
      
    volumes:
      - /volume1/docker/penpot/assets:/opt/data/assets:rw

    depends_on:
      - penpot-postgres
      - penpot-redis

    networks:
      - penpot

    ## Configuration envronment variables for backend the
    ## container.

    environment:
      ## Relevant flags for backend:
      ## - demo-users
      ## - email-verification
      ## - log-emails
      ## - log-invitation-tokens
      ## - login-with-github
      ## - login-with-gitlab
      ## - login-with-google
      ## - login-with-ldap
      ## - login-with-oidc
      ## - login-with-password
      ## - registration
      ## - secure-session-cookies
      ## - smtp
      ## - smtp-debug
      ## - telemetry
      ## - webhooks
      ## - prepl-server
      ##
      ## You can read more about all available flags and other
      ## environment variables for the backend here:
      ## https://help.penpot.app/technical-guide/configuration/#advanced-configuration

      - PENPOT_FLAGS=disable-secure-session-cookies enable-registration enable-login-with-gitlab enable-insecure-register disable-login-with-password disable-email-verification enable-smtp enable-prepl-server

      - PENPOT_GITLAB_BASE_URI=https://git.domain.com
      - PENPOT_GITLAB_CLIENT_ID=itsasecret
      - PENPOT_GITLAB_CLIENT_SECRET=itsasecret

      ## Penpot SECRET KEY. It serves as a master key from which other keys for subsystems
      ## (eg http sessions, or invitations) are derived.
      ##
      ## If you leve it commented, all created sessions and invitations will
      ## become invalid on container restart.
      ##
      ## If you going to uncomment this, we recommend use here a trully randomly generated
      ## 512 bits base64 encoded string.  You can generate one with:
      ##
      ## python3 -c "import secrets; print(secrets.token_urlsafe(64))"

      ## Set this to a RANDOM string to secure your installation, e.g. using "pwgen -s 64"
      ## This environment variable is necessary since PenPot 2.4.0
      - PENPOT_SECRET_KEY:itsasecret

      ## The PREPL host. Mainly used for external programatic access to penpot backend
      ## (example: admin). By default it listen on `localhost` but if you are going to use
      ## the `admin`, you will need to uncomment this and set the host to `0.0.0.0`.

      ## - PENPOT_PREPL_HOST=0.0.0.0

      ## Public URI. If you are going to expose this instance to the internet and use it
      ## under different domain than 'localhost', you will need to adjust it to the final
      ## domain.
      ##
      ## Consider using traefik and set the 'disable-secure-session-cookies' if you are
      ## not going to serve penpot under HTTPS.

      - PENPOT_PUBLIC_URI=https://penpot.domain.com

      ## Database connection parameters. Don't touch them unless you are using custom
      ## postgresql connection parameters.

      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot

      ## Redis is used for the websockets notifications. Don't touch unless the redis
      ## container has different parameters or different name.

      - PENPOT_REDIS_URI=redis://penpot-redis/0

      ## Default configuration for assets storage: using filesystem based with all files
      ## stored in a docker volume.

      #- PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      #- PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets

      ## Also can be configured to to use a S3 compatible storage
      ## service like MiniIO. Look below for minio service setup.

      - AWS_ACCESS_KEY_ID=itsasecret
      - AWS_SECRET_ACCESS_KEY=itsasecret
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-s3
      - PENPOT_STORAGE_ASSETS_S3_ENDPOINT=https://minio.domain.com:9000
      - PENPOT_STORAGE_ASSETS_S3_REGION=au-east-1
      - PENPOT_STORAGE_ASSETS_S3_BUCKET=penpot

      ## Telemetry. When enabled, a periodical process will send anonymous data about this
      ## instance. Telemetry data will enable us to learn on how the application is used,
      ## based on real scenarios. If you want to help us, please leave it enabled. You can
      ## audit what data we send with the code available on github

      - PENPOT_TELEMETRY_ENABLED=false

      ## Example SMTP/Email configuration. By default, emails are sent to the mailcatch
      ## service, but for production usage is recommended to setup a real SMTP
      ## provider. Emails are used to confirm user registrations & invitations. Look below
      ## how mailcatch service is configured.

      - PENPOT_SMTP_DEFAULT_FROM=Penpot <incoming@support.domain.com>
      - PENPOT_SMTP_DEFAULT_REPLY_TO=Penpot <incoming@support.domain.com>
      - PENPOT_SMTP_HOST=smtp.office365.com
      - PENPOT_SMTP_PORT=587
      - PENPOT_SMTP_USERNAME=incoming@support.domain.com
      - PENPOT_SMTP_PASSWORD=itsasecret
      - PENPOT_SMTP_TLS=true
      - PENPOT_SMTP_SSL=false

  penpot-exporter:
    image: "penpotapp/exporter:2.4.1"
    restart: always
    
    security_opt:
      - no-new-privileges:true
      
    networks:
      - penpot

    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=https://penpot.domain.com

      ## Redis is used for the websockets notifications.
      - PENPOT_REDIS_URI=redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT
    
    security_opt:
      - no-new-privileges:true
      
    volumes:
      - /volume1/docker/penpot/db:/var/lib/postgresql/data:rw

    networks:
      - penpot

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

  penpot-redis:
    image: redis:7.2
    restart: always
    networks:
      - penpot

  ## A mailcatch service, used as temporal SMTP server. You can access via HTTP to the
  ## port 1080 for read all emails the penpot platform has sent. Should be only used as a
  ## temporal solution meanwhile you don't have a real SMTP provider configured.

  #penpot-mailcatch:
  #  image: sj26/mailcatcher:latest
  #  restart: always
  #  expose:
  #    - "1025"
  #  ports:
  #    - "1080:1080"
  #  networks:
  #    - penpot

  ## Example configuration of MiniIO (S3 compatible object storage service); If you don't
  ## have preference, then just use filesystem, this is here just for the completeness.

  # minio:
  #   image: "minio/minio:latest"
  #   command: minio server /mnt/data --console-address ":9001"
  #   restart: always
  #
  #   volumes:
  #     - "penpot_minio:/mnt/data"
  #
  #   environment:
  #     - MINIO_ROOT_USER=minioadmin
  #     - MINIO_ROOT_PASSWORD=minioadmin
  #
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
```
