### ISSUE TITLE
bug: Font tab's font family styling is inconsistent

### ISSUE THREAD

**Issue by jiu-virgil** [uxbox/uxbox#5768]
### Steps To Reproduce

When uploading a font family with multiple weights in the `Fonts` tab, the elements that display the different weights are only spaced horizontally.

### Expected behavior

The elements should probably be spaced in both axis to ensure consistency and a more pleasant look.

This happens because vertical spacing probably wasn't considered, as this simple css fixes it.

```scss
.main_ui_dashboard_fonts__variant {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.5rem 0.75rem;
    padding-right: 0.75rem;
  cursor: pointer;
  margin-top: 0.3rem; /* (+) <----- */
}
```

This is an issue in [`frontend/src/app/main/ui/dashboard/fonts.scss`](https://github.com/penpot/penpot/blob/develop/frontend/src/app/main/ui/dashboard/fonts.scss)
more specifically in `.variant` on line 133.

i suggest adding something like this

```scss
.variant {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: $s-8 $s-12;
  cursor: pointer;
  gap: $s-4;
  margin: $s-4 0 0 0; /* (+) <----- */
  .icon {
    display: flex;
    align-items: center;

/* (...) */
```

### Actual behavior

It's just cramped there.

### Screenshots or video

What it looks like:

![Image](https://github.com/user-attachments/assets/88933ae7-3fb3-41c6-9e31-5f9723f04686)

What it would look like:

![Image](https://github.com/user-attachments/assets/e2346f2a-e596-4c8e-8164-da27e1a6226b)

### Desktop (please complete the following information)

- OS: Windows 11 (23H2)
- Browser & version: Zen 1.7.4b (Firefox 134.0.2)

### Frontend Stack Trace

```console

```

### Backend Stack Trace

```console

```
