### ISSUE TITLE
Trouble logging in with OIDC, one particular user

### ISSUE THREAD

**Issue by eancarr** [uxbox/uxbox#5892]
Hello,

First, thanks for Penpot. It's superb.

I've set up Penpot with Authentik using OIDC. It's working for me to log in as well as another user. But for a third user, I'm having a really hard time.

When I click the OpenID button under Log into my account, it redirects to Authentik, then back to Penpot where it prompts me to put in the full name. After I click the button, it doesn't do anything. I click the button again and it takes me to an email verification screen.

The backend logs say:

```
2025-02-18T15:19:39.724624534Z [2025-02-18 15:19:39.723] I app.main - hint="welcome to penpot", flags="backend-openapi-doc,backend-api-doc,secure-session-cookies,v2-migration,oidc-registration,backend-worker,login-with-oidc,smtp,email-verification,registration,prepl-server", worker?=true, version="2.3.3"
2025-02-18T15:25:05.051219211Z [2025-02-18 15:25:05.050] W app.rpc.commands.auth - hint="repeated registry detected", profile-id="842d379e-c8f8-81f0-8005-c1ae7ea187d2", profile-email="xxx@xxx.com", context-action="ignore"
```

I have tried using `python3 manage.py delete-profile` to delete that email address and try again, but the same thing happens.

Sometimes I get an Oops! 404 error page instead.

My flags are:

```
PENPOT_BACKEND_FLAGS=enable-login-with-oidc enable-oidc-registration enable-smtp enable-prepl-server disable-login-with-password
PENPOT_FRONTEND_FLAGS=enable-login-with-oidc enable-oidc-registration disable-login-with-password
```
Docker Compose is below.
```
services:
  frontend:
    image: 'penpotapp/frontend:2.3.3'
    volumes:
      - '/mnt/HC_Volume_101963257/data/coolify/persistent_data/penpot/penpot-assets:/opt/data/assets'
    depends_on:
      penpot-backend:
        condition: service_healthy
      penpot-exporter:
        condition: service_healthy
    environment:
      - SERVICE_FQDN_FRONTEND
      - 'PENPOT_FLAGS=${PENPOT_FRONTEND_FLAGS:-enable-login-with-password}'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 30s
      timeout: 60s
      retries: 15
    labels:
      - traefik.enable=true
      - traefik.http.routers.penpot-https.entrypoints=https
      - traefik.http.routers.penpot-https.rule=Host(`penpot.xxx.xxx`)
      - traefik.http.routers.penpot-https.tls=true
      - traefik.http.routers.penpot-https.tls.certresolver=letsencrypt
      - traefik.http.routers.penpot-https.service=penpot-https
      - traefik.http.services.penpot-https.loadbalancer.server.port=80
      - traefik.http.services.penpot-https.loadbalancer.passhostheader=true
  penpot-backend:
    image: 'penpotapp/backend:2.3.3'
    volumes:
      - '/mnt/HC_Volume_101963257/data/coolify/persistent_data/penpot/penpot-assets:/opt/data/assets'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - 'PENPOT_FLAGS=${PENPOT_BACKEND_FLAGS}'
      - PENPOT_HTTP_SERVER_PORT=6060
      - PENPOT_SECRET_KEY=$SERVICE_REALBASE64_64_PENPOT
      - PENPOT_PUBLIC_URI=$SERVICE_FQDN_FRONTEND
      - 'PENPOT_BACKEND_URI=http://penpot-backend'
      - 'PENPOT_EXPORTER_URI=http://penpot-exporter'
      - 'PENPOT_DATABASE_URI=postgresql://postgres/${POSTGRES_DB:-penpot}'
      - 'PENPOT_DATABASE_USERNAME=${SERVICE_USER_POSTGRES}'
      - 'PENPOT_DATABASE_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'PENPOT_REDIS_URI=redis://redis/0'
      - 'PENPOT_TELEMETRY_ENABLED=${PENPOT_TELEMETRY_ENABLED:-false}'
      - 'PENPOT_SMTP_DEFAULT_FROM=${PENPOT_SMTP_DEFAULT_FROM:-no-reply@example.com}'
      - 'PENPOT_SMTP_DEFAULT_REPLY_TO=${PENPOT_SMTP_DEFAULT_REPLY_TO:-no-reply@example.com}'
      - 'PENPOT_SMTP_HOST=${PENPOT_SMTP_HOST:-mailpit}'
      - 'PENPOT_SMTP_PORT=${PENPOT_SMTP_PORT:-1025}'
      - 'PENPOT_SMTP_USERNAME=${PENPOT_SMTP_USERNAME:-penpot}'
      - 'PENPOT_SMTP_PASSWORD=${PENPOT_SMTP_PASSWORD:-penpot}'
      - 'PENPOT_SMTP_TLS=${PENPOT_SMTP_TLS:-false}'
      - 'PENPOT_SMTP_SSL=${PENPOT_SMTP_SSL:-false}'
      - PENPOT_OIDC_CLIENT_ID=xxxxxx
      - 'PENPOT_OIDC_BASE_URI=https://authentik.xxx.xxx/application/o/penpot/'
      - 'PENPOT_OIDC_CLIENT_SECRET=${PENPOT_OIDC_CLIENT_SECRET}'
      - 'PENPOT_OIDC_AUTH_URI=https://authentik.xxx.xxx/application/o/authorize/'
      - 'PENPOT_OIDC_TOKEN_URI=https://authentik.xxx.xxx/application/o/token/'
      - 'PENPOT_OIDC_USER_URI=https://authentik.xxx.xxx/application/o/userinfo/'
      - PENPOT_OIDC_ROLES=
      - PENPOT_OIDC_ROLES_ATTR=
      - 'PENPOT_OIDC_SCOPES=openid profile email'
      - PENPOT_OIDC_NAME_ATTR=preferred_username
      - PENPOT_OIDC_EMAIL_ATTR=email
      - AWS_ACCESS_KEY_ID=xxxx
      - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-s3
      - PENPOT_STORAGE_ASSETS_S3_BUCKET=xxxx
      - PENPOT_STORAGE_ASSETS_S3_REGION=xx-xxx-1
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:6060/readyz'
      interval: 30s
      timeout: 60s
      retries: 15
  penpot-exporter:
    image: 'penpotapp/exporter:2.3.3'
    environment:
      - PENPOT_PUBLIC_URI=$SERVICE_FQDN_FRONTEND
      - 'PENPOT_REDIS_URI=redis://redis/0'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:6061/readyz'
      interval: 2s
      timeout: 10s
      retries: 15
  postgres:
    image: 'postgres:15'
    volumes:
      - '/mnt/HC_Volume_101963257/data/coolify/persistent_data/penpot/penpot-postgresql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - 'POSTGRES_DB=${POSTGRES_DB:-penpot}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
  redis:
    image: 'redis:7-alpine'
    command: 'redis-server --appendonly yes'
    volumes:
      - '/mnt/HC_Volume_101963257/data/coolify/persistent_data/penpot/penpot-redis-data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 20s
      retries: 10
```

Thank you for any advice!
