### ISSUE TITLE
Storybook UI is missing a scrollbar

### ISSUE THREAD

**Issue by fdabrao** [uxbox/uxbox#6049]
### Steps To Reproduce

1. Open http://localhost:6006
2. Try to scroll in the first page

### Expected behavior

Have scrollbar

### Actual behavior

No scrollbar apearing

### Screenshots or video

https://github.com/user-attachments/assets/0a3fa5b7-46b7-40bd-bfeb-6028b34bc5e8

### Environment (please complete the following information)

- WSL2 Ubunto 24.04.
- Docker Destop Windows 4.39.0

### Frontend Stack Trace

```console

```

### Backend Stack Trace

```console

```

### Additional context

frontend/resources/templates/preview-head.mustache
Change to:
```css
<link href="./css/ds.css?ts={{& ts}}" rel="stylesheet" type="text/css" />

<style>
  body {
    overflow-y: scroll;
  }

  #storybook-root {
    height: 100%;
    overflow: auto;
  }

  #storybook-docs {
    height: 100%;
    overflow: auto;
  }

</style>

<script>
  window.penpotTranslations = JSON.parse({{& translations}});
</script>
```
